// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexfileservice

import (
	kitexfileservice "aim/kitex_gen/kitexfileservice"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateFile": kitex.NewMethodInfo(
		createFileHandler,
		newKitexFileServiceCreateFileArgs,
		newKitexFileServiceCreateFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteFile": kitex.NewMethodInfo(
		deleteFileHandler,
		newKitexFileServiceDeleteFileArgs,
		newKitexFileServiceDeleteFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFile": kitex.NewMethodInfo(
		getFileHandler,
		newKitexFileServiceGetFileArgs,
		newKitexFileServiceGetFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	kitexFileServiceServiceInfo                = NewServiceInfo()
	kitexFileServiceServiceInfoForClient       = NewServiceInfoForClient()
	kitexFileServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return kitexFileServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return kitexFileServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return kitexFileServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KitexFileService"
	handlerType := (*kitexfileservice.KitexFileService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kitexfileservice",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexfileservice.KitexFileServiceCreateFileArgs)
	realResult := result.(*kitexfileservice.KitexFileServiceCreateFileResult)
	success, err := handler.(kitexfileservice.KitexFileService).CreateFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexFileServiceCreateFileArgs() interface{} {
	return kitexfileservice.NewKitexFileServiceCreateFileArgs()
}

func newKitexFileServiceCreateFileResult() interface{} {
	return kitexfileservice.NewKitexFileServiceCreateFileResult()
}

func deleteFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexfileservice.KitexFileServiceDeleteFileArgs)
	realResult := result.(*kitexfileservice.KitexFileServiceDeleteFileResult)
	success, err := handler.(kitexfileservice.KitexFileService).DeleteFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexFileServiceDeleteFileArgs() interface{} {
	return kitexfileservice.NewKitexFileServiceDeleteFileArgs()
}

func newKitexFileServiceDeleteFileResult() interface{} {
	return kitexfileservice.NewKitexFileServiceDeleteFileResult()
}

func getFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexfileservice.KitexFileServiceGetFileArgs)
	realResult := result.(*kitexfileservice.KitexFileServiceGetFileResult)
	success, err := handler.(kitexfileservice.KitexFileService).GetFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexFileServiceGetFileArgs() interface{} {
	return kitexfileservice.NewKitexFileServiceGetFileArgs()
}

func newKitexFileServiceGetFileResult() interface{} {
	return kitexfileservice.NewKitexFileServiceGetFileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateFile(ctx context.Context, req *kitexfileservice.CreateFileReq) (r *kitexfileservice.CreateFileResp, err error) {
	var _args kitexfileservice.KitexFileServiceCreateFileArgs
	_args.Req = req
	var _result kitexfileservice.KitexFileServiceCreateFileResult
	if err = p.c.Call(ctx, "CreateFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFile(ctx context.Context, req *kitexfileservice.DeleteFileReq) (r *kitexfileservice.DeleteFileResp, err error) {
	var _args kitexfileservice.KitexFileServiceDeleteFileArgs
	_args.Req = req
	var _result kitexfileservice.KitexFileServiceDeleteFileResult
	if err = p.c.Call(ctx, "DeleteFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFile(ctx context.Context, req *kitexfileservice.GetFileReq) (r *kitexfileservice.GetFileResp, err error) {
	var _args kitexfileservice.KitexFileServiceGetFileArgs
	_args.Req = req
	var _result kitexfileservice.KitexFileServiceGetFileResult
	if err = p.c.Call(ctx, "GetFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
