// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexfileservice

import (
	"aim/kitex_gen/kitexcommonmodel"
	"context"
	"fmt"
)

type CreateFileReq struct {
	CommonInfo              *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	FileName                string                       `thrift:"file_name,2" frugal:"2,default,string" json:"file_name"`
	DataStream              []byte                       `thrift:"data_stream,3" frugal:"3,default,binary" json:"data_stream"`
	FileType                string                       `thrift:"file_type,4" frugal:"4,default,string" json:"file_type"`
	ContentType             string                       `thrift:"content_type,5" frugal:"5,default,string" json:"content_type"`
	VoiceDurationTimeSecond int64                        `thrift:"voice_duration_time_second,6" frugal:"6,default,i64" json:"voice_duration_time_second"`
}

func NewCreateFileReq() *CreateFileReq {
	return &CreateFileReq{}
}

func (p *CreateFileReq) InitDefault() {
}

var CreateFileReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *CreateFileReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return CreateFileReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *CreateFileReq) GetFileName() (v string) {
	return p.FileName
}

func (p *CreateFileReq) GetDataStream() (v []byte) {
	return p.DataStream
}

func (p *CreateFileReq) GetFileType() (v string) {
	return p.FileType
}

func (p *CreateFileReq) GetContentType() (v string) {
	return p.ContentType
}

func (p *CreateFileReq) GetVoiceDurationTimeSecond() (v int64) {
	return p.VoiceDurationTimeSecond
}
func (p *CreateFileReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *CreateFileReq) SetFileName(val string) {
	p.FileName = val
}
func (p *CreateFileReq) SetDataStream(val []byte) {
	p.DataStream = val
}
func (p *CreateFileReq) SetFileType(val string) {
	p.FileType = val
}
func (p *CreateFileReq) SetContentType(val string) {
	p.ContentType = val
}
func (p *CreateFileReq) SetVoiceDurationTimeSecond(val int64) {
	p.VoiceDurationTimeSecond = val
}

func (p *CreateFileReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *CreateFileReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateFileReq(%+v)", *p)
}

var fieldIDToName_CreateFileReq = map[int16]string{
	1: "common_info",
	2: "file_name",
	3: "data_stream",
	4: "file_type",
	5: "content_type",
	6: "voice_duration_time_second",
}

type CreateFileResp struct {
	FileId int64 `thrift:"file_id,1" frugal:"1,default,i64" json:"file_id"`
}

func NewCreateFileResp() *CreateFileResp {
	return &CreateFileResp{}
}

func (p *CreateFileResp) InitDefault() {
}

func (p *CreateFileResp) GetFileId() (v int64) {
	return p.FileId
}
func (p *CreateFileResp) SetFileId(val int64) {
	p.FileId = val
}

func (p *CreateFileResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateFileResp(%+v)", *p)
}

var fieldIDToName_CreateFileResp = map[int16]string{
	1: "file_id",
}

type DeleteFileReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	FileId     int64                        `thrift:"file_id,2" frugal:"2,default,i64" json:"file_id"`
}

func NewDeleteFileReq() *DeleteFileReq {
	return &DeleteFileReq{}
}

func (p *DeleteFileReq) InitDefault() {
}

var DeleteFileReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *DeleteFileReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return DeleteFileReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *DeleteFileReq) GetFileId() (v int64) {
	return p.FileId
}
func (p *DeleteFileReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *DeleteFileReq) SetFileId(val int64) {
	p.FileId = val
}

func (p *DeleteFileReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *DeleteFileReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFileReq(%+v)", *p)
}

var fieldIDToName_DeleteFileReq = map[int16]string{
	1: "common_info",
	2: "file_id",
}

type DeleteFileResp struct {
}

func NewDeleteFileResp() *DeleteFileResp {
	return &DeleteFileResp{}
}

func (p *DeleteFileResp) InitDefault() {
}

func (p *DeleteFileResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFileResp(%+v)", *p)
}

var fieldIDToName_DeleteFileResp = map[int16]string{}

type GetFileReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	FileId     int64                        `thrift:"file_id,2" frugal:"2,default,i64" json:"file_id"`
}

func NewGetFileReq() *GetFileReq {
	return &GetFileReq{}
}

func (p *GetFileReq) InitDefault() {
}

var GetFileReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetFileReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetFileReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetFileReq) GetFileId() (v int64) {
	return p.FileId
}
func (p *GetFileReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetFileReq) SetFileId(val int64) {
	p.FileId = val
}

func (p *GetFileReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetFileReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFileReq(%+v)", *p)
}

var fieldIDToName_GetFileReq = map[int16]string{
	1: "common_info",
	2: "file_id",
}

type GetFileResp struct {
	DataStream  []byte `thrift:"data_stream,1" frugal:"1,default,binary" json:"data_stream"`
	ContentType string `thrift:"content_type,2" frugal:"2,default,string" json:"content_type"`
}

func NewGetFileResp() *GetFileResp {
	return &GetFileResp{}
}

func (p *GetFileResp) InitDefault() {
}

func (p *GetFileResp) GetDataStream() (v []byte) {
	return p.DataStream
}

func (p *GetFileResp) GetContentType() (v string) {
	return p.ContentType
}
func (p *GetFileResp) SetDataStream(val []byte) {
	p.DataStream = val
}
func (p *GetFileResp) SetContentType(val string) {
	p.ContentType = val
}

func (p *GetFileResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFileResp(%+v)", *p)
}

var fieldIDToName_GetFileResp = map[int16]string{
	1: "data_stream",
	2: "content_type",
}

type KitexFileService interface {
	CreateFile(ctx context.Context, req *CreateFileReq) (r *CreateFileResp, err error)

	DeleteFile(ctx context.Context, req *DeleteFileReq) (r *DeleteFileResp, err error)

	GetFile(ctx context.Context, req *GetFileReq) (r *GetFileResp, err error)
}

type KitexFileServiceCreateFileArgs struct {
	Req *CreateFileReq `thrift:"req,1" frugal:"1,default,CreateFileReq" json:"req"`
}

func NewKitexFileServiceCreateFileArgs() *KitexFileServiceCreateFileArgs {
	return &KitexFileServiceCreateFileArgs{}
}

func (p *KitexFileServiceCreateFileArgs) InitDefault() {
}

var KitexFileServiceCreateFileArgs_Req_DEFAULT *CreateFileReq

func (p *KitexFileServiceCreateFileArgs) GetReq() (v *CreateFileReq) {
	if !p.IsSetReq() {
		return KitexFileServiceCreateFileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexFileServiceCreateFileArgs) SetReq(val *CreateFileReq) {
	p.Req = val
}

func (p *KitexFileServiceCreateFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexFileServiceCreateFileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexFileServiceCreateFileArgs(%+v)", *p)
}

var fieldIDToName_KitexFileServiceCreateFileArgs = map[int16]string{
	1: "req",
}

type KitexFileServiceCreateFileResult struct {
	Success *CreateFileResp `thrift:"success,0,optional" frugal:"0,optional,CreateFileResp" json:"success,omitempty"`
}

func NewKitexFileServiceCreateFileResult() *KitexFileServiceCreateFileResult {
	return &KitexFileServiceCreateFileResult{}
}

func (p *KitexFileServiceCreateFileResult) InitDefault() {
}

var KitexFileServiceCreateFileResult_Success_DEFAULT *CreateFileResp

func (p *KitexFileServiceCreateFileResult) GetSuccess() (v *CreateFileResp) {
	if !p.IsSetSuccess() {
		return KitexFileServiceCreateFileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexFileServiceCreateFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateFileResp)
}

func (p *KitexFileServiceCreateFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexFileServiceCreateFileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexFileServiceCreateFileResult(%+v)", *p)
}

var fieldIDToName_KitexFileServiceCreateFileResult = map[int16]string{
	0: "success",
}

type KitexFileServiceDeleteFileArgs struct {
	Req *DeleteFileReq `thrift:"req,1" frugal:"1,default,DeleteFileReq" json:"req"`
}

func NewKitexFileServiceDeleteFileArgs() *KitexFileServiceDeleteFileArgs {
	return &KitexFileServiceDeleteFileArgs{}
}

func (p *KitexFileServiceDeleteFileArgs) InitDefault() {
}

var KitexFileServiceDeleteFileArgs_Req_DEFAULT *DeleteFileReq

func (p *KitexFileServiceDeleteFileArgs) GetReq() (v *DeleteFileReq) {
	if !p.IsSetReq() {
		return KitexFileServiceDeleteFileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexFileServiceDeleteFileArgs) SetReq(val *DeleteFileReq) {
	p.Req = val
}

func (p *KitexFileServiceDeleteFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexFileServiceDeleteFileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexFileServiceDeleteFileArgs(%+v)", *p)
}

var fieldIDToName_KitexFileServiceDeleteFileArgs = map[int16]string{
	1: "req",
}

type KitexFileServiceDeleteFileResult struct {
	Success *DeleteFileResp `thrift:"success,0,optional" frugal:"0,optional,DeleteFileResp" json:"success,omitempty"`
}

func NewKitexFileServiceDeleteFileResult() *KitexFileServiceDeleteFileResult {
	return &KitexFileServiceDeleteFileResult{}
}

func (p *KitexFileServiceDeleteFileResult) InitDefault() {
}

var KitexFileServiceDeleteFileResult_Success_DEFAULT *DeleteFileResp

func (p *KitexFileServiceDeleteFileResult) GetSuccess() (v *DeleteFileResp) {
	if !p.IsSetSuccess() {
		return KitexFileServiceDeleteFileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexFileServiceDeleteFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteFileResp)
}

func (p *KitexFileServiceDeleteFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexFileServiceDeleteFileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexFileServiceDeleteFileResult(%+v)", *p)
}

var fieldIDToName_KitexFileServiceDeleteFileResult = map[int16]string{
	0: "success",
}

type KitexFileServiceGetFileArgs struct {
	Req *GetFileReq `thrift:"req,1" frugal:"1,default,GetFileReq" json:"req"`
}

func NewKitexFileServiceGetFileArgs() *KitexFileServiceGetFileArgs {
	return &KitexFileServiceGetFileArgs{}
}

func (p *KitexFileServiceGetFileArgs) InitDefault() {
}

var KitexFileServiceGetFileArgs_Req_DEFAULT *GetFileReq

func (p *KitexFileServiceGetFileArgs) GetReq() (v *GetFileReq) {
	if !p.IsSetReq() {
		return KitexFileServiceGetFileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexFileServiceGetFileArgs) SetReq(val *GetFileReq) {
	p.Req = val
}

func (p *KitexFileServiceGetFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexFileServiceGetFileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexFileServiceGetFileArgs(%+v)", *p)
}

var fieldIDToName_KitexFileServiceGetFileArgs = map[int16]string{
	1: "req",
}

type KitexFileServiceGetFileResult struct {
	Success *GetFileResp `thrift:"success,0,optional" frugal:"0,optional,GetFileResp" json:"success,omitempty"`
}

func NewKitexFileServiceGetFileResult() *KitexFileServiceGetFileResult {
	return &KitexFileServiceGetFileResult{}
}

func (p *KitexFileServiceGetFileResult) InitDefault() {
}

var KitexFileServiceGetFileResult_Success_DEFAULT *GetFileResp

func (p *KitexFileServiceGetFileResult) GetSuccess() (v *GetFileResp) {
	if !p.IsSetSuccess() {
		return KitexFileServiceGetFileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexFileServiceGetFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFileResp)
}

func (p *KitexFileServiceGetFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexFileServiceGetFileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexFileServiceGetFileResult(%+v)", *p)
}

var fieldIDToName_KitexFileServiceGetFileResult = map[int16]string{
	0: "success",
}
