// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexaiservice

import (
	"aim/kitex_gen/kitexcommonmodel"
	"context"
	"fmt"
)

type SendMessageToAiReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	GroupId    int64                        `thrift:"group_id,3" frugal:"3,default,i64" json:"group_id"`
	Message    string                       `thrift:"message,4" frugal:"4,default,string" json:"message"`
}

func NewSendMessageToAiReq() *SendMessageToAiReq {
	return &SendMessageToAiReq{}
}

func (p *SendMessageToAiReq) InitDefault() {
}

var SendMessageToAiReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *SendMessageToAiReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return SendMessageToAiReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *SendMessageToAiReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SendMessageToAiReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *SendMessageToAiReq) GetMessage() (v string) {
	return p.Message
}
func (p *SendMessageToAiReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *SendMessageToAiReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SendMessageToAiReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *SendMessageToAiReq) SetMessage(val string) {
	p.Message = val
}

func (p *SendMessageToAiReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *SendMessageToAiReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMessageToAiReq(%+v)", *p)
}

var fieldIDToName_SendMessageToAiReq = map[int16]string{
	1: "common_info",
	2: "user_id",
	3: "group_id",
	4: "message",
}

type SendMessageToAiResp struct {
}

func NewSendMessageToAiResp() *SendMessageToAiResp {
	return &SendMessageToAiResp{}
}

func (p *SendMessageToAiResp) InitDefault() {
}

func (p *SendMessageToAiResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMessageToAiResp(%+v)", *p)
}

var fieldIDToName_SendMessageToAiResp = map[int16]string{}

type DeleteChatContextReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewDeleteChatContextReq() *DeleteChatContextReq {
	return &DeleteChatContextReq{}
}

func (p *DeleteChatContextReq) InitDefault() {
}

var DeleteChatContextReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *DeleteChatContextReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return DeleteChatContextReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *DeleteChatContextReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *DeleteChatContextReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *DeleteChatContextReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *DeleteChatContextReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *DeleteChatContextReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteChatContextReq(%+v)", *p)
}

var fieldIDToName_DeleteChatContextReq = map[int16]string{
	1: "common_info",
	2: "user_id",
}

type DeleteChatContextResp struct {
}

func NewDeleteChatContextResp() *DeleteChatContextResp {
	return &DeleteChatContextResp{}
}

func (p *DeleteChatContextResp) InitDefault() {
}

func (p *DeleteChatContextResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteChatContextResp(%+v)", *p)
}

var fieldIDToName_DeleteChatContextResp = map[int16]string{}

type GetAiConfigReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewGetAiConfigReq() *GetAiConfigReq {
	return &GetAiConfigReq{}
}

func (p *GetAiConfigReq) InitDefault() {
}

var GetAiConfigReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetAiConfigReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetAiConfigReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetAiConfigReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetAiConfigReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetAiConfigReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetAiConfigReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetAiConfigReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAiConfigReq(%+v)", *p)
}

var fieldIDToName_GetAiConfigReq = map[int16]string{
	1: "common_info",
	2: "user_id",
}

type GetAiConfigResp struct {
	ModelName string `thrift:"model_name,1" frugal:"1,default,string" json:"model_name"`
	BaseUrl   string `thrift:"base_url,2" frugal:"2,default,string" json:"base_url"`
	ApiKey    string `thrift:"api_key,3" frugal:"3,default,string" json:"api_key"`
	Role      string `thrift:"role,4" frugal:"4,default,string" json:"role"`
	Prompt    string `thrift:"prompt,5" frugal:"5,default,string" json:"prompt"`
}

func NewGetAiConfigResp() *GetAiConfigResp {
	return &GetAiConfigResp{}
}

func (p *GetAiConfigResp) InitDefault() {
}

func (p *GetAiConfigResp) GetModelName() (v string) {
	return p.ModelName
}

func (p *GetAiConfigResp) GetBaseUrl() (v string) {
	return p.BaseUrl
}

func (p *GetAiConfigResp) GetApiKey() (v string) {
	return p.ApiKey
}

func (p *GetAiConfigResp) GetRole() (v string) {
	return p.Role
}

func (p *GetAiConfigResp) GetPrompt() (v string) {
	return p.Prompt
}
func (p *GetAiConfigResp) SetModelName(val string) {
	p.ModelName = val
}
func (p *GetAiConfigResp) SetBaseUrl(val string) {
	p.BaseUrl = val
}
func (p *GetAiConfigResp) SetApiKey(val string) {
	p.ApiKey = val
}
func (p *GetAiConfigResp) SetRole(val string) {
	p.Role = val
}
func (p *GetAiConfigResp) SetPrompt(val string) {
	p.Prompt = val
}

func (p *GetAiConfigResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAiConfigResp(%+v)", *p)
}

var fieldIDToName_GetAiConfigResp = map[int16]string{
	1: "model_name",
	2: "base_url",
	3: "api_key",
	4: "role",
	5: "prompt",
}

type UpdateAiConfigReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	ModelName  string                       `thrift:"model_name,3" frugal:"3,default,string" json:"model_name"`
	BaseUrl    string                       `thrift:"base_url,4" frugal:"4,default,string" json:"base_url"`
	ApiKey     string                       `thrift:"api_key,5" frugal:"5,default,string" json:"api_key"`
	Role       string                       `thrift:"role,6" frugal:"6,default,string" json:"role"`
	Prompt     string                       `thrift:"prompt,7" frugal:"7,default,string" json:"prompt"`
}

func NewUpdateAiConfigReq() *UpdateAiConfigReq {
	return &UpdateAiConfigReq{}
}

func (p *UpdateAiConfigReq) InitDefault() {
}

var UpdateAiConfigReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *UpdateAiConfigReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return UpdateAiConfigReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *UpdateAiConfigReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateAiConfigReq) GetModelName() (v string) {
	return p.ModelName
}

func (p *UpdateAiConfigReq) GetBaseUrl() (v string) {
	return p.BaseUrl
}

func (p *UpdateAiConfigReq) GetApiKey() (v string) {
	return p.ApiKey
}

func (p *UpdateAiConfigReq) GetRole() (v string) {
	return p.Role
}

func (p *UpdateAiConfigReq) GetPrompt() (v string) {
	return p.Prompt
}
func (p *UpdateAiConfigReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *UpdateAiConfigReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateAiConfigReq) SetModelName(val string) {
	p.ModelName = val
}
func (p *UpdateAiConfigReq) SetBaseUrl(val string) {
	p.BaseUrl = val
}
func (p *UpdateAiConfigReq) SetApiKey(val string) {
	p.ApiKey = val
}
func (p *UpdateAiConfigReq) SetRole(val string) {
	p.Role = val
}
func (p *UpdateAiConfigReq) SetPrompt(val string) {
	p.Prompt = val
}

func (p *UpdateAiConfigReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *UpdateAiConfigReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAiConfigReq(%+v)", *p)
}

var fieldIDToName_UpdateAiConfigReq = map[int16]string{
	1: "common_info",
	2: "user_id",
	3: "model_name",
	4: "base_url",
	5: "api_key",
	6: "role",
	7: "prompt",
}

type UpdateAiConfigResp struct {
}

func NewUpdateAiConfigResp() *UpdateAiConfigResp {
	return &UpdateAiConfigResp{}
}

func (p *UpdateAiConfigResp) InitDefault() {
}

func (p *UpdateAiConfigResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAiConfigResp(%+v)", *p)
}

var fieldIDToName_UpdateAiConfigResp = map[int16]string{}

type DeleteAiConfigReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewDeleteAiConfigReq() *DeleteAiConfigReq {
	return &DeleteAiConfigReq{}
}

func (p *DeleteAiConfigReq) InitDefault() {
}

var DeleteAiConfigReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *DeleteAiConfigReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return DeleteAiConfigReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *DeleteAiConfigReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *DeleteAiConfigReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *DeleteAiConfigReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *DeleteAiConfigReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *DeleteAiConfigReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAiConfigReq(%+v)", *p)
}

var fieldIDToName_DeleteAiConfigReq = map[int16]string{
	1: "common_info",
	2: "user_id",
}

type DeleteAiConfigResp struct {
}

func NewDeleteAiConfigResp() *DeleteAiConfigResp {
	return &DeleteAiConfigResp{}
}

func (p *DeleteAiConfigResp) InitDefault() {
}

func (p *DeleteAiConfigResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAiConfigResp(%+v)", *p)
}

var fieldIDToName_DeleteAiConfigResp = map[int16]string{}

type KitexAiService interface {
	SendMessageToAi(ctx context.Context, req *SendMessageToAiReq) (r *SendMessageToAiResp, err error)

	DeleteChatContext(ctx context.Context, req *DeleteChatContextReq) (r *DeleteChatContextResp, err error)

	GetAiConfig(ctx context.Context, req *GetAiConfigReq) (r *GetAiConfigResp, err error)

	UpdateAiConfig(ctx context.Context, req *UpdateAiConfigReq) (r *UpdateAiConfigResp, err error)

	DeleteAiConfig(ctx context.Context, req *DeleteAiConfigReq) (r *DeleteAiConfigResp, err error)
}

type KitexAiServiceSendMessageToAiArgs struct {
	Req *SendMessageToAiReq `thrift:"req,1" frugal:"1,default,SendMessageToAiReq" json:"req"`
}

func NewKitexAiServiceSendMessageToAiArgs() *KitexAiServiceSendMessageToAiArgs {
	return &KitexAiServiceSendMessageToAiArgs{}
}

func (p *KitexAiServiceSendMessageToAiArgs) InitDefault() {
}

var KitexAiServiceSendMessageToAiArgs_Req_DEFAULT *SendMessageToAiReq

func (p *KitexAiServiceSendMessageToAiArgs) GetReq() (v *SendMessageToAiReq) {
	if !p.IsSetReq() {
		return KitexAiServiceSendMessageToAiArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexAiServiceSendMessageToAiArgs) SetReq(val *SendMessageToAiReq) {
	p.Req = val
}

func (p *KitexAiServiceSendMessageToAiArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexAiServiceSendMessageToAiArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceSendMessageToAiArgs(%+v)", *p)
}

var fieldIDToName_KitexAiServiceSendMessageToAiArgs = map[int16]string{
	1: "req",
}

type KitexAiServiceSendMessageToAiResult struct {
	Success *SendMessageToAiResp `thrift:"success,0,optional" frugal:"0,optional,SendMessageToAiResp" json:"success,omitempty"`
}

func NewKitexAiServiceSendMessageToAiResult() *KitexAiServiceSendMessageToAiResult {
	return &KitexAiServiceSendMessageToAiResult{}
}

func (p *KitexAiServiceSendMessageToAiResult) InitDefault() {
}

var KitexAiServiceSendMessageToAiResult_Success_DEFAULT *SendMessageToAiResp

func (p *KitexAiServiceSendMessageToAiResult) GetSuccess() (v *SendMessageToAiResp) {
	if !p.IsSetSuccess() {
		return KitexAiServiceSendMessageToAiResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexAiServiceSendMessageToAiResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendMessageToAiResp)
}

func (p *KitexAiServiceSendMessageToAiResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexAiServiceSendMessageToAiResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceSendMessageToAiResult(%+v)", *p)
}

var fieldIDToName_KitexAiServiceSendMessageToAiResult = map[int16]string{
	0: "success",
}

type KitexAiServiceDeleteChatContextArgs struct {
	Req *DeleteChatContextReq `thrift:"req,1" frugal:"1,default,DeleteChatContextReq" json:"req"`
}

func NewKitexAiServiceDeleteChatContextArgs() *KitexAiServiceDeleteChatContextArgs {
	return &KitexAiServiceDeleteChatContextArgs{}
}

func (p *KitexAiServiceDeleteChatContextArgs) InitDefault() {
}

var KitexAiServiceDeleteChatContextArgs_Req_DEFAULT *DeleteChatContextReq

func (p *KitexAiServiceDeleteChatContextArgs) GetReq() (v *DeleteChatContextReq) {
	if !p.IsSetReq() {
		return KitexAiServiceDeleteChatContextArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexAiServiceDeleteChatContextArgs) SetReq(val *DeleteChatContextReq) {
	p.Req = val
}

func (p *KitexAiServiceDeleteChatContextArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexAiServiceDeleteChatContextArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceDeleteChatContextArgs(%+v)", *p)
}

var fieldIDToName_KitexAiServiceDeleteChatContextArgs = map[int16]string{
	1: "req",
}

type KitexAiServiceDeleteChatContextResult struct {
	Success *DeleteChatContextResp `thrift:"success,0,optional" frugal:"0,optional,DeleteChatContextResp" json:"success,omitempty"`
}

func NewKitexAiServiceDeleteChatContextResult() *KitexAiServiceDeleteChatContextResult {
	return &KitexAiServiceDeleteChatContextResult{}
}

func (p *KitexAiServiceDeleteChatContextResult) InitDefault() {
}

var KitexAiServiceDeleteChatContextResult_Success_DEFAULT *DeleteChatContextResp

func (p *KitexAiServiceDeleteChatContextResult) GetSuccess() (v *DeleteChatContextResp) {
	if !p.IsSetSuccess() {
		return KitexAiServiceDeleteChatContextResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexAiServiceDeleteChatContextResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteChatContextResp)
}

func (p *KitexAiServiceDeleteChatContextResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexAiServiceDeleteChatContextResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceDeleteChatContextResult(%+v)", *p)
}

var fieldIDToName_KitexAiServiceDeleteChatContextResult = map[int16]string{
	0: "success",
}

type KitexAiServiceGetAiConfigArgs struct {
	Req *GetAiConfigReq `thrift:"req,1" frugal:"1,default,GetAiConfigReq" json:"req"`
}

func NewKitexAiServiceGetAiConfigArgs() *KitexAiServiceGetAiConfigArgs {
	return &KitexAiServiceGetAiConfigArgs{}
}

func (p *KitexAiServiceGetAiConfigArgs) InitDefault() {
}

var KitexAiServiceGetAiConfigArgs_Req_DEFAULT *GetAiConfigReq

func (p *KitexAiServiceGetAiConfigArgs) GetReq() (v *GetAiConfigReq) {
	if !p.IsSetReq() {
		return KitexAiServiceGetAiConfigArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexAiServiceGetAiConfigArgs) SetReq(val *GetAiConfigReq) {
	p.Req = val
}

func (p *KitexAiServiceGetAiConfigArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexAiServiceGetAiConfigArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceGetAiConfigArgs(%+v)", *p)
}

var fieldIDToName_KitexAiServiceGetAiConfigArgs = map[int16]string{
	1: "req",
}

type KitexAiServiceGetAiConfigResult struct {
	Success *GetAiConfigResp `thrift:"success,0,optional" frugal:"0,optional,GetAiConfigResp" json:"success,omitempty"`
}

func NewKitexAiServiceGetAiConfigResult() *KitexAiServiceGetAiConfigResult {
	return &KitexAiServiceGetAiConfigResult{}
}

func (p *KitexAiServiceGetAiConfigResult) InitDefault() {
}

var KitexAiServiceGetAiConfigResult_Success_DEFAULT *GetAiConfigResp

func (p *KitexAiServiceGetAiConfigResult) GetSuccess() (v *GetAiConfigResp) {
	if !p.IsSetSuccess() {
		return KitexAiServiceGetAiConfigResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexAiServiceGetAiConfigResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAiConfigResp)
}

func (p *KitexAiServiceGetAiConfigResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexAiServiceGetAiConfigResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceGetAiConfigResult(%+v)", *p)
}

var fieldIDToName_KitexAiServiceGetAiConfigResult = map[int16]string{
	0: "success",
}

type KitexAiServiceUpdateAiConfigArgs struct {
	Req *UpdateAiConfigReq `thrift:"req,1" frugal:"1,default,UpdateAiConfigReq" json:"req"`
}

func NewKitexAiServiceUpdateAiConfigArgs() *KitexAiServiceUpdateAiConfigArgs {
	return &KitexAiServiceUpdateAiConfigArgs{}
}

func (p *KitexAiServiceUpdateAiConfigArgs) InitDefault() {
}

var KitexAiServiceUpdateAiConfigArgs_Req_DEFAULT *UpdateAiConfigReq

func (p *KitexAiServiceUpdateAiConfigArgs) GetReq() (v *UpdateAiConfigReq) {
	if !p.IsSetReq() {
		return KitexAiServiceUpdateAiConfigArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexAiServiceUpdateAiConfigArgs) SetReq(val *UpdateAiConfigReq) {
	p.Req = val
}

func (p *KitexAiServiceUpdateAiConfigArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexAiServiceUpdateAiConfigArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceUpdateAiConfigArgs(%+v)", *p)
}

var fieldIDToName_KitexAiServiceUpdateAiConfigArgs = map[int16]string{
	1: "req",
}

type KitexAiServiceUpdateAiConfigResult struct {
	Success *UpdateAiConfigResp `thrift:"success,0,optional" frugal:"0,optional,UpdateAiConfigResp" json:"success,omitempty"`
}

func NewKitexAiServiceUpdateAiConfigResult() *KitexAiServiceUpdateAiConfigResult {
	return &KitexAiServiceUpdateAiConfigResult{}
}

func (p *KitexAiServiceUpdateAiConfigResult) InitDefault() {
}

var KitexAiServiceUpdateAiConfigResult_Success_DEFAULT *UpdateAiConfigResp

func (p *KitexAiServiceUpdateAiConfigResult) GetSuccess() (v *UpdateAiConfigResp) {
	if !p.IsSetSuccess() {
		return KitexAiServiceUpdateAiConfigResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexAiServiceUpdateAiConfigResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateAiConfigResp)
}

func (p *KitexAiServiceUpdateAiConfigResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexAiServiceUpdateAiConfigResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceUpdateAiConfigResult(%+v)", *p)
}

var fieldIDToName_KitexAiServiceUpdateAiConfigResult = map[int16]string{
	0: "success",
}

type KitexAiServiceDeleteAiConfigArgs struct {
	Req *DeleteAiConfigReq `thrift:"req,1" frugal:"1,default,DeleteAiConfigReq" json:"req"`
}

func NewKitexAiServiceDeleteAiConfigArgs() *KitexAiServiceDeleteAiConfigArgs {
	return &KitexAiServiceDeleteAiConfigArgs{}
}

func (p *KitexAiServiceDeleteAiConfigArgs) InitDefault() {
}

var KitexAiServiceDeleteAiConfigArgs_Req_DEFAULT *DeleteAiConfigReq

func (p *KitexAiServiceDeleteAiConfigArgs) GetReq() (v *DeleteAiConfigReq) {
	if !p.IsSetReq() {
		return KitexAiServiceDeleteAiConfigArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexAiServiceDeleteAiConfigArgs) SetReq(val *DeleteAiConfigReq) {
	p.Req = val
}

func (p *KitexAiServiceDeleteAiConfigArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexAiServiceDeleteAiConfigArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceDeleteAiConfigArgs(%+v)", *p)
}

var fieldIDToName_KitexAiServiceDeleteAiConfigArgs = map[int16]string{
	1: "req",
}

type KitexAiServiceDeleteAiConfigResult struct {
	Success *DeleteAiConfigResp `thrift:"success,0,optional" frugal:"0,optional,DeleteAiConfigResp" json:"success,omitempty"`
}

func NewKitexAiServiceDeleteAiConfigResult() *KitexAiServiceDeleteAiConfigResult {
	return &KitexAiServiceDeleteAiConfigResult{}
}

func (p *KitexAiServiceDeleteAiConfigResult) InitDefault() {
}

var KitexAiServiceDeleteAiConfigResult_Success_DEFAULT *DeleteAiConfigResp

func (p *KitexAiServiceDeleteAiConfigResult) GetSuccess() (v *DeleteAiConfigResp) {
	if !p.IsSetSuccess() {
		return KitexAiServiceDeleteAiConfigResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexAiServiceDeleteAiConfigResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteAiConfigResp)
}

func (p *KitexAiServiceDeleteAiConfigResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexAiServiceDeleteAiConfigResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexAiServiceDeleteAiConfigResult(%+v)", *p)
}

var fieldIDToName_KitexAiServiceDeleteAiConfigResult = map[int16]string{
	0: "success",
}
