// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexuserservice

import (
	"aim/kitex_gen/kitexcommonmodel"
	"context"
	"fmt"
)

type GetUserInfoReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

var GetUserInfoReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetUserInfoReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetUserInfoReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetUserInfoReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserInfoReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetUserInfoReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserInfoReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "common_info",
	2: "user_id",
}

type GetUserInfoResp struct {
	UserInfo   *kitexcommonmodel.UserInfo     `thrift:"user_info,1" frugal:"1,default,kitexcommonmodel.UserInfo" json:"user_info"`
	RemarkInfo []*kitexcommonmodel.RemarkInfo `thrift:"remark_info,2" frugal:"2,default,list<kitexcommonmodel.RemarkInfo>" json:"remark_info"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

var GetUserInfoResp_UserInfo_DEFAULT *kitexcommonmodel.UserInfo

func (p *GetUserInfoResp) GetUserInfo() (v *kitexcommonmodel.UserInfo) {
	if !p.IsSetUserInfo() {
		return GetUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}

func (p *GetUserInfoResp) GetRemarkInfo() (v []*kitexcommonmodel.RemarkInfo) {
	return p.RemarkInfo
}
func (p *GetUserInfoResp) SetUserInfo(val *kitexcommonmodel.UserInfo) {
	p.UserInfo = val
}
func (p *GetUserInfoResp) SetRemarkInfo(val []*kitexcommonmodel.RemarkInfo) {
	p.RemarkInfo = val
}

func (p *GetUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "user_info",
	2: "remark_info",
}

type GetOtherUserInfoReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GoalUserId int64                        `thrift:"goal_user_id,2" frugal:"2,default,i64" json:"goal_user_id"`
}

func NewGetOtherUserInfoReq() *GetOtherUserInfoReq {
	return &GetOtherUserInfoReq{}
}

func (p *GetOtherUserInfoReq) InitDefault() {
}

var GetOtherUserInfoReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetOtherUserInfoReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetOtherUserInfoReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetOtherUserInfoReq) GetGoalUserId() (v int64) {
	return p.GoalUserId
}
func (p *GetOtherUserInfoReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetOtherUserInfoReq) SetGoalUserId(val int64) {
	p.GoalUserId = val
}

func (p *GetOtherUserInfoReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetOtherUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOtherUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetOtherUserInfoReq = map[int16]string{
	1: "common_info",
	2: "goal_user_id",
}

type GetOtherUserInfoResp struct {
	UserInfo *kitexcommonmodel.UserInfo `thrift:"user_info,1" frugal:"1,default,kitexcommonmodel.UserInfo" json:"user_info"`
}

func NewGetOtherUserInfoResp() *GetOtherUserInfoResp {
	return &GetOtherUserInfoResp{}
}

func (p *GetOtherUserInfoResp) InitDefault() {
}

var GetOtherUserInfoResp_UserInfo_DEFAULT *kitexcommonmodel.UserInfo

func (p *GetOtherUserInfoResp) GetUserInfo() (v *kitexcommonmodel.UserInfo) {
	if !p.IsSetUserInfo() {
		return GetOtherUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *GetOtherUserInfoResp) SetUserInfo(val *kitexcommonmodel.UserInfo) {
	p.UserInfo = val
}

func (p *GetOtherUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetOtherUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOtherUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetOtherUserInfoResp = map[int16]string{
	1: "user_info",
}

type UpdateUserInfoReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserInfo   *kitexcommonmodel.UserInfo   `thrift:"user_info,2" frugal:"2,default,kitexcommonmodel.UserInfo" json:"user_info"`
}

func NewUpdateUserInfoReq() *UpdateUserInfoReq {
	return &UpdateUserInfoReq{}
}

func (p *UpdateUserInfoReq) InitDefault() {
}

var UpdateUserInfoReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *UpdateUserInfoReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return UpdateUserInfoReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

var UpdateUserInfoReq_UserInfo_DEFAULT *kitexcommonmodel.UserInfo

func (p *UpdateUserInfoReq) GetUserInfo() (v *kitexcommonmodel.UserInfo) {
	if !p.IsSetUserInfo() {
		return UpdateUserInfoReq_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *UpdateUserInfoReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *UpdateUserInfoReq) SetUserInfo(val *kitexcommonmodel.UserInfo) {
	p.UserInfo = val
}

func (p *UpdateUserInfoReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *UpdateUserInfoReq) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *UpdateUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoReq(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoReq = map[int16]string{
	1: "common_info",
	2: "user_info",
}

type UpdateUserInfoResp struct {
}

func NewUpdateUserInfoResp() *UpdateUserInfoResp {
	return &UpdateUserInfoResp{}
}

func (p *UpdateUserInfoResp) InitDefault() {
}

func (p *UpdateUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoResp(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoResp = map[int16]string{}

type RemarkReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	RemarkInfo *kitexcommonmodel.RemarkInfo `thrift:"remark_info,2" frugal:"2,default,kitexcommonmodel.RemarkInfo" json:"remark_info"`
}

func NewRemarkReq() *RemarkReq {
	return &RemarkReq{}
}

func (p *RemarkReq) InitDefault() {
}

var RemarkReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *RemarkReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return RemarkReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

var RemarkReq_RemarkInfo_DEFAULT *kitexcommonmodel.RemarkInfo

func (p *RemarkReq) GetRemarkInfo() (v *kitexcommonmodel.RemarkInfo) {
	if !p.IsSetRemarkInfo() {
		return RemarkReq_RemarkInfo_DEFAULT
	}
	return p.RemarkInfo
}
func (p *RemarkReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *RemarkReq) SetRemarkInfo(val *kitexcommonmodel.RemarkInfo) {
	p.RemarkInfo = val
}

func (p *RemarkReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *RemarkReq) IsSetRemarkInfo() bool {
	return p.RemarkInfo != nil
}

func (p *RemarkReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemarkReq(%+v)", *p)
}

var fieldIDToName_RemarkReq = map[int16]string{
	1: "common_info",
	2: "remark_info",
}

type RemarkResp struct {
}

func NewRemarkResp() *RemarkResp {
	return &RemarkResp{}
}

func (p *RemarkResp) InitDefault() {
}

func (p *RemarkResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemarkResp(%+v)", *p)
}

var fieldIDToName_RemarkResp = map[int16]string{}

type RegisterReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	Password   string                       `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

var RegisterReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *RegisterReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return RegisterReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "common_info",
	2: "password",
}

type RegisterResp struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

func (p *RegisterResp) GetUserId() (v int64) {
	return p.UserId
}
func (p *RegisterResp) SetUserId(val int64) {
	p.UserId = val
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "user_id",
}

type LoginReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Password   string                       `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

var LoginReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *LoginReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return LoginReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *LoginReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *LoginReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "common_info",
	2: "user_id",
	3: "password",
}

type LoginResp struct {
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{}

type KitexUserService interface {
	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	GetOtherUserInfo(ctx context.Context, req *GetOtherUserInfoReq) (r *GetOtherUserInfoResp, err error)

	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq) (r *UpdateUserInfoResp, err error)

	Remark(ctx context.Context, req *RemarkReq) (r *RemarkResp, err error)

	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)
}

type KitexUserServiceGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewKitexUserServiceGetUserInfoArgs() *KitexUserServiceGetUserInfoArgs {
	return &KitexUserServiceGetUserInfoArgs{}
}

func (p *KitexUserServiceGetUserInfoArgs) InitDefault() {
}

var KitexUserServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *KitexUserServiceGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return KitexUserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexUserServiceGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *KitexUserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexUserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_KitexUserServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type KitexUserServiceGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewKitexUserServiceGetUserInfoResult() *KitexUserServiceGetUserInfoResult {
	return &KitexUserServiceGetUserInfoResult{}
}

func (p *KitexUserServiceGetUserInfoResult) InitDefault() {
}

var KitexUserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *KitexUserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return KitexUserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexUserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *KitexUserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexUserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_KitexUserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}

type KitexUserServiceGetOtherUserInfoArgs struct {
	Req *GetOtherUserInfoReq `thrift:"req,1" frugal:"1,default,GetOtherUserInfoReq" json:"req"`
}

func NewKitexUserServiceGetOtherUserInfoArgs() *KitexUserServiceGetOtherUserInfoArgs {
	return &KitexUserServiceGetOtherUserInfoArgs{}
}

func (p *KitexUserServiceGetOtherUserInfoArgs) InitDefault() {
}

var KitexUserServiceGetOtherUserInfoArgs_Req_DEFAULT *GetOtherUserInfoReq

func (p *KitexUserServiceGetOtherUserInfoArgs) GetReq() (v *GetOtherUserInfoReq) {
	if !p.IsSetReq() {
		return KitexUserServiceGetOtherUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexUserServiceGetOtherUserInfoArgs) SetReq(val *GetOtherUserInfoReq) {
	p.Req = val
}

func (p *KitexUserServiceGetOtherUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexUserServiceGetOtherUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceGetOtherUserInfoArgs(%+v)", *p)
}

var fieldIDToName_KitexUserServiceGetOtherUserInfoArgs = map[int16]string{
	1: "req",
}

type KitexUserServiceGetOtherUserInfoResult struct {
	Success *GetOtherUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetOtherUserInfoResp" json:"success,omitempty"`
}

func NewKitexUserServiceGetOtherUserInfoResult() *KitexUserServiceGetOtherUserInfoResult {
	return &KitexUserServiceGetOtherUserInfoResult{}
}

func (p *KitexUserServiceGetOtherUserInfoResult) InitDefault() {
}

var KitexUserServiceGetOtherUserInfoResult_Success_DEFAULT *GetOtherUserInfoResp

func (p *KitexUserServiceGetOtherUserInfoResult) GetSuccess() (v *GetOtherUserInfoResp) {
	if !p.IsSetSuccess() {
		return KitexUserServiceGetOtherUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexUserServiceGetOtherUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOtherUserInfoResp)
}

func (p *KitexUserServiceGetOtherUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexUserServiceGetOtherUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceGetOtherUserInfoResult(%+v)", *p)
}

var fieldIDToName_KitexUserServiceGetOtherUserInfoResult = map[int16]string{
	0: "success",
}

type KitexUserServiceUpdateUserInfoArgs struct {
	Req *UpdateUserInfoReq `thrift:"req,1" frugal:"1,default,UpdateUserInfoReq" json:"req"`
}

func NewKitexUserServiceUpdateUserInfoArgs() *KitexUserServiceUpdateUserInfoArgs {
	return &KitexUserServiceUpdateUserInfoArgs{}
}

func (p *KitexUserServiceUpdateUserInfoArgs) InitDefault() {
}

var KitexUserServiceUpdateUserInfoArgs_Req_DEFAULT *UpdateUserInfoReq

func (p *KitexUserServiceUpdateUserInfoArgs) GetReq() (v *UpdateUserInfoReq) {
	if !p.IsSetReq() {
		return KitexUserServiceUpdateUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexUserServiceUpdateUserInfoArgs) SetReq(val *UpdateUserInfoReq) {
	p.Req = val
}

func (p *KitexUserServiceUpdateUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexUserServiceUpdateUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceUpdateUserInfoArgs(%+v)", *p)
}

var fieldIDToName_KitexUserServiceUpdateUserInfoArgs = map[int16]string{
	1: "req",
}

type KitexUserServiceUpdateUserInfoResult struct {
	Success *UpdateUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,UpdateUserInfoResp" json:"success,omitempty"`
}

func NewKitexUserServiceUpdateUserInfoResult() *KitexUserServiceUpdateUserInfoResult {
	return &KitexUserServiceUpdateUserInfoResult{}
}

func (p *KitexUserServiceUpdateUserInfoResult) InitDefault() {
}

var KitexUserServiceUpdateUserInfoResult_Success_DEFAULT *UpdateUserInfoResp

func (p *KitexUserServiceUpdateUserInfoResult) GetSuccess() (v *UpdateUserInfoResp) {
	if !p.IsSetSuccess() {
		return KitexUserServiceUpdateUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexUserServiceUpdateUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserInfoResp)
}

func (p *KitexUserServiceUpdateUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexUserServiceUpdateUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceUpdateUserInfoResult(%+v)", *p)
}

var fieldIDToName_KitexUserServiceUpdateUserInfoResult = map[int16]string{
	0: "success",
}

type KitexUserServiceRemarkArgs struct {
	Req *RemarkReq `thrift:"req,1" frugal:"1,default,RemarkReq" json:"req"`
}

func NewKitexUserServiceRemarkArgs() *KitexUserServiceRemarkArgs {
	return &KitexUserServiceRemarkArgs{}
}

func (p *KitexUserServiceRemarkArgs) InitDefault() {
}

var KitexUserServiceRemarkArgs_Req_DEFAULT *RemarkReq

func (p *KitexUserServiceRemarkArgs) GetReq() (v *RemarkReq) {
	if !p.IsSetReq() {
		return KitexUserServiceRemarkArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexUserServiceRemarkArgs) SetReq(val *RemarkReq) {
	p.Req = val
}

func (p *KitexUserServiceRemarkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexUserServiceRemarkArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceRemarkArgs(%+v)", *p)
}

var fieldIDToName_KitexUserServiceRemarkArgs = map[int16]string{
	1: "req",
}

type KitexUserServiceRemarkResult struct {
	Success *RemarkResp `thrift:"success,0,optional" frugal:"0,optional,RemarkResp" json:"success,omitempty"`
}

func NewKitexUserServiceRemarkResult() *KitexUserServiceRemarkResult {
	return &KitexUserServiceRemarkResult{}
}

func (p *KitexUserServiceRemarkResult) InitDefault() {
}

var KitexUserServiceRemarkResult_Success_DEFAULT *RemarkResp

func (p *KitexUserServiceRemarkResult) GetSuccess() (v *RemarkResp) {
	if !p.IsSetSuccess() {
		return KitexUserServiceRemarkResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexUserServiceRemarkResult) SetSuccess(x interface{}) {
	p.Success = x.(*RemarkResp)
}

func (p *KitexUserServiceRemarkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexUserServiceRemarkResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceRemarkResult(%+v)", *p)
}

var fieldIDToName_KitexUserServiceRemarkResult = map[int16]string{
	0: "success",
}

type KitexUserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewKitexUserServiceRegisterArgs() *KitexUserServiceRegisterArgs {
	return &KitexUserServiceRegisterArgs{}
}

func (p *KitexUserServiceRegisterArgs) InitDefault() {
}

var KitexUserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *KitexUserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return KitexUserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexUserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *KitexUserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexUserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_KitexUserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type KitexUserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewKitexUserServiceRegisterResult() *KitexUserServiceRegisterResult {
	return &KitexUserServiceRegisterResult{}
}

func (p *KitexUserServiceRegisterResult) InitDefault() {
}

var KitexUserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *KitexUserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return KitexUserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexUserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *KitexUserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexUserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_KitexUserServiceRegisterResult = map[int16]string{
	0: "success",
}

type KitexUserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewKitexUserServiceLoginArgs() *KitexUserServiceLoginArgs {
	return &KitexUserServiceLoginArgs{}
}

func (p *KitexUserServiceLoginArgs) InitDefault() {
}

var KitexUserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *KitexUserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return KitexUserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexUserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *KitexUserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexUserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_KitexUserServiceLoginArgs = map[int16]string{
	1: "req",
}

type KitexUserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewKitexUserServiceLoginResult() *KitexUserServiceLoginResult {
	return &KitexUserServiceLoginResult{}
}

func (p *KitexUserServiceLoginResult) InitDefault() {
}

var KitexUserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *KitexUserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return KitexUserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexUserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *KitexUserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexUserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexUserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_KitexUserServiceLoginResult = map[int16]string{
	0: "success",
}
