// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexuserservice

import (
	kitexuserservice "aim/kitex_gen/kitexuserservice"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newKitexUserServiceGetUserInfoArgs,
		newKitexUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOtherUserInfo": kitex.NewMethodInfo(
		getOtherUserInfoHandler,
		newKitexUserServiceGetOtherUserInfoArgs,
		newKitexUserServiceGetOtherUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInfo": kitex.NewMethodInfo(
		updateUserInfoHandler,
		newKitexUserServiceUpdateUserInfoArgs,
		newKitexUserServiceUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Remark": kitex.NewMethodInfo(
		remarkHandler,
		newKitexUserServiceRemarkArgs,
		newKitexUserServiceRemarkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newKitexUserServiceRegisterArgs,
		newKitexUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newKitexUserServiceLoginArgs,
		newKitexUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	kitexUserServiceServiceInfo                = NewServiceInfo()
	kitexUserServiceServiceInfoForClient       = NewServiceInfoForClient()
	kitexUserServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return kitexUserServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return kitexUserServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return kitexUserServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KitexUserService"
	handlerType := (*kitexuserservice.KitexUserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kitexuserservice",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.KitexUserServiceGetUserInfoArgs)
	realResult := result.(*kitexuserservice.KitexUserServiceGetUserInfoResult)
	success, err := handler.(kitexuserservice.KitexUserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexUserServiceGetUserInfoArgs() interface{} {
	return kitexuserservice.NewKitexUserServiceGetUserInfoArgs()
}

func newKitexUserServiceGetUserInfoResult() interface{} {
	return kitexuserservice.NewKitexUserServiceGetUserInfoResult()
}

func getOtherUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.KitexUserServiceGetOtherUserInfoArgs)
	realResult := result.(*kitexuserservice.KitexUserServiceGetOtherUserInfoResult)
	success, err := handler.(kitexuserservice.KitexUserService).GetOtherUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexUserServiceGetOtherUserInfoArgs() interface{} {
	return kitexuserservice.NewKitexUserServiceGetOtherUserInfoArgs()
}

func newKitexUserServiceGetOtherUserInfoResult() interface{} {
	return kitexuserservice.NewKitexUserServiceGetOtherUserInfoResult()
}

func updateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.KitexUserServiceUpdateUserInfoArgs)
	realResult := result.(*kitexuserservice.KitexUserServiceUpdateUserInfoResult)
	success, err := handler.(kitexuserservice.KitexUserService).UpdateUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexUserServiceUpdateUserInfoArgs() interface{} {
	return kitexuserservice.NewKitexUserServiceUpdateUserInfoArgs()
}

func newKitexUserServiceUpdateUserInfoResult() interface{} {
	return kitexuserservice.NewKitexUserServiceUpdateUserInfoResult()
}

func remarkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.KitexUserServiceRemarkArgs)
	realResult := result.(*kitexuserservice.KitexUserServiceRemarkResult)
	success, err := handler.(kitexuserservice.KitexUserService).Remark(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexUserServiceRemarkArgs() interface{} {
	return kitexuserservice.NewKitexUserServiceRemarkArgs()
}

func newKitexUserServiceRemarkResult() interface{} {
	return kitexuserservice.NewKitexUserServiceRemarkResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.KitexUserServiceRegisterArgs)
	realResult := result.(*kitexuserservice.KitexUserServiceRegisterResult)
	success, err := handler.(kitexuserservice.KitexUserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexUserServiceRegisterArgs() interface{} {
	return kitexuserservice.NewKitexUserServiceRegisterArgs()
}

func newKitexUserServiceRegisterResult() interface{} {
	return kitexuserservice.NewKitexUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.KitexUserServiceLoginArgs)
	realResult := result.(*kitexuserservice.KitexUserServiceLoginResult)
	success, err := handler.(kitexuserservice.KitexUserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexUserServiceLoginArgs() interface{} {
	return kitexuserservice.NewKitexUserServiceLoginArgs()
}

func newKitexUserServiceLoginResult() interface{} {
	return kitexuserservice.NewKitexUserServiceLoginResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUserInfo(ctx context.Context, req *kitexuserservice.GetUserInfoReq) (r *kitexuserservice.GetUserInfoResp, err error) {
	var _args kitexuserservice.KitexUserServiceGetUserInfoArgs
	_args.Req = req
	var _result kitexuserservice.KitexUserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOtherUserInfo(ctx context.Context, req *kitexuserservice.GetOtherUserInfoReq) (r *kitexuserservice.GetOtherUserInfoResp, err error) {
	var _args kitexuserservice.KitexUserServiceGetOtherUserInfoArgs
	_args.Req = req
	var _result kitexuserservice.KitexUserServiceGetOtherUserInfoResult
	if err = p.c.Call(ctx, "GetOtherUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInfo(ctx context.Context, req *kitexuserservice.UpdateUserInfoReq) (r *kitexuserservice.UpdateUserInfoResp, err error) {
	var _args kitexuserservice.KitexUserServiceUpdateUserInfoArgs
	_args.Req = req
	var _result kitexuserservice.KitexUserServiceUpdateUserInfoResult
	if err = p.c.Call(ctx, "UpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Remark(ctx context.Context, req *kitexuserservice.RemarkReq) (r *kitexuserservice.RemarkResp, err error) {
	var _args kitexuserservice.KitexUserServiceRemarkArgs
	_args.Req = req
	var _result kitexuserservice.KitexUserServiceRemarkResult
	if err = p.c.Call(ctx, "Remark", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *kitexuserservice.RegisterReq) (r *kitexuserservice.RegisterResp, err error) {
	var _args kitexuserservice.KitexUserServiceRegisterArgs
	_args.Req = req
	var _result kitexuserservice.KitexUserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *kitexuserservice.LoginReq) (r *kitexuserservice.LoginResp, err error) {
	var _args kitexuserservice.KitexUserServiceLoginArgs
	_args.Req = req
	var _result kitexuserservice.KitexUserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
