// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexmessageservice

import (
	"aim/kitex_gen/kitexcommonmodel"
	"context"
	"fmt"
)

type SendMessageReq struct {
	CommonInfo     *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId        int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId         int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	MessageContent string                       `thrift:"message_content,4" frugal:"4,default,string" json:"message_content"`
	IsAi           bool                         `thrift:"is_ai,5" frugal:"5,default,bool" json:"is_ai"`
}

func NewSendMessageReq() *SendMessageReq {
	return &SendMessageReq{}
}

func (p *SendMessageReq) InitDefault() {
}

var SendMessageReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *SendMessageReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return SendMessageReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *SendMessageReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *SendMessageReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SendMessageReq) GetMessageContent() (v string) {
	return p.MessageContent
}

func (p *SendMessageReq) GetIsAi() (v bool) {
	return p.IsAi
}
func (p *SendMessageReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *SendMessageReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *SendMessageReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SendMessageReq) SetMessageContent(val string) {
	p.MessageContent = val
}
func (p *SendMessageReq) SetIsAi(val bool) {
	p.IsAi = val
}

func (p *SendMessageReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *SendMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMessageReq(%+v)", *p)
}

var fieldIDToName_SendMessageReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
	4: "message_content",
	5: "is_ai",
}

type SendMessageResp struct {
	MessageId int64 `thrift:"message_id,1" frugal:"1,default,i64" json:"message_id"`
}

func NewSendMessageResp() *SendMessageResp {
	return &SendMessageResp{}
}

func (p *SendMessageResp) InitDefault() {
}

func (p *SendMessageResp) GetMessageId() (v int64) {
	return p.MessageId
}
func (p *SendMessageResp) SetMessageId(val int64) {
	p.MessageId = val
}

func (p *SendMessageResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMessageResp(%+v)", *p)
}

var fieldIDToName_SendMessageResp = map[int16]string{
	1: "message_id",
}

type SendFileReq struct {
	CommonInfo  *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId     int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId      int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	FileName    string                       `thrift:"file_name,4" frugal:"4,default,string" json:"file_name"`
	ContentType string                       `thrift:"content_type,5" frugal:"5,default,string" json:"content_type"`
	DataStream  []byte                       `thrift:"data_stream,6" frugal:"6,default,binary" json:"data_stream"`
}

func NewSendFileReq() *SendFileReq {
	return &SendFileReq{}
}

func (p *SendFileReq) InitDefault() {
}

var SendFileReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *SendFileReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return SendFileReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *SendFileReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *SendFileReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SendFileReq) GetFileName() (v string) {
	return p.FileName
}

func (p *SendFileReq) GetContentType() (v string) {
	return p.ContentType
}

func (p *SendFileReq) GetDataStream() (v []byte) {
	return p.DataStream
}
func (p *SendFileReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *SendFileReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *SendFileReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SendFileReq) SetFileName(val string) {
	p.FileName = val
}
func (p *SendFileReq) SetContentType(val string) {
	p.ContentType = val
}
func (p *SendFileReq) SetDataStream(val []byte) {
	p.DataStream = val
}

func (p *SendFileReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *SendFileReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendFileReq(%+v)", *p)
}

var fieldIDToName_SendFileReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
	4: "file_name",
	5: "content_type",
	6: "data_stream",
}

type SendFileResp struct {
	MessageId int64 `thrift:"message_id,1" frugal:"1,default,i64" json:"message_id"`
}

func NewSendFileResp() *SendFileResp {
	return &SendFileResp{}
}

func (p *SendFileResp) InitDefault() {
}

func (p *SendFileResp) GetMessageId() (v int64) {
	return p.MessageId
}
func (p *SendFileResp) SetMessageId(val int64) {
	p.MessageId = val
}

func (p *SendFileResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendFileResp(%+v)", *p)
}

var fieldIDToName_SendFileResp = map[int16]string{
	1: "message_id",
}

type SendVoiceReq struct {
	CommonInfo      *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId         int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId          int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	ContentType     string                       `thrift:"content_type,4" frugal:"4,default,string" json:"content_type"`
	VoiceTimeSecond int64                        `thrift:"voice_time_second,5" frugal:"5,default,i64" json:"voice_time_second"`
	DataStream      []byte                       `thrift:"data_stream,6" frugal:"6,default,binary" json:"data_stream"`
}

func NewSendVoiceReq() *SendVoiceReq {
	return &SendVoiceReq{}
}

func (p *SendVoiceReq) InitDefault() {
}

var SendVoiceReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *SendVoiceReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return SendVoiceReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *SendVoiceReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *SendVoiceReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SendVoiceReq) GetContentType() (v string) {
	return p.ContentType
}

func (p *SendVoiceReq) GetVoiceTimeSecond() (v int64) {
	return p.VoiceTimeSecond
}

func (p *SendVoiceReq) GetDataStream() (v []byte) {
	return p.DataStream
}
func (p *SendVoiceReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *SendVoiceReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *SendVoiceReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SendVoiceReq) SetContentType(val string) {
	p.ContentType = val
}
func (p *SendVoiceReq) SetVoiceTimeSecond(val int64) {
	p.VoiceTimeSecond = val
}
func (p *SendVoiceReq) SetDataStream(val []byte) {
	p.DataStream = val
}

func (p *SendVoiceReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *SendVoiceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendVoiceReq(%+v)", *p)
}

var fieldIDToName_SendVoiceReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
	4: "content_type",
	5: "voice_time_second",
	6: "data_stream",
}

type SendVoiceResp struct {
	MessageId int64 `thrift:"message_id,1" frugal:"1,default,i64" json:"message_id"`
}

func NewSendVoiceResp() *SendVoiceResp {
	return &SendVoiceResp{}
}

func (p *SendVoiceResp) InitDefault() {
}

func (p *SendVoiceResp) GetMessageId() (v int64) {
	return p.MessageId
}
func (p *SendVoiceResp) SetMessageId(val int64) {
	p.MessageId = val
}

func (p *SendVoiceResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendVoiceResp(%+v)", *p)
}

var fieldIDToName_SendVoiceResp = map[int16]string{
	1: "message_id",
}

type SendPictureReq struct {
	CommonInfo  *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId     int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId      int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	ContentType string                       `thrift:"content_type,4" frugal:"4,default,string" json:"content_type"`
	DataStream  []byte                       `thrift:"data_stream,5" frugal:"5,default,binary" json:"data_stream"`
}

func NewSendPictureReq() *SendPictureReq {
	return &SendPictureReq{}
}

func (p *SendPictureReq) InitDefault() {
}

var SendPictureReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *SendPictureReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return SendPictureReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *SendPictureReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *SendPictureReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SendPictureReq) GetContentType() (v string) {
	return p.ContentType
}

func (p *SendPictureReq) GetDataStream() (v []byte) {
	return p.DataStream
}
func (p *SendPictureReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *SendPictureReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *SendPictureReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SendPictureReq) SetContentType(val string) {
	p.ContentType = val
}
func (p *SendPictureReq) SetDataStream(val []byte) {
	p.DataStream = val
}

func (p *SendPictureReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *SendPictureReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendPictureReq(%+v)", *p)
}

var fieldIDToName_SendPictureReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
	4: "content_type",
	5: "data_stream",
}

type SendPictureResp struct {
	MessageId int64 `thrift:"message_id,1" frugal:"1,default,i64" json:"message_id"`
}

func NewSendPictureResp() *SendPictureResp {
	return &SendPictureResp{}
}

func (p *SendPictureResp) InitDefault() {
}

func (p *SendPictureResp) GetMessageId() (v int64) {
	return p.MessageId
}
func (p *SendPictureResp) SetMessageId(val int64) {
	p.MessageId = val
}

func (p *SendPictureResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendPictureResp(%+v)", *p)
}

var fieldIDToName_SendPictureResp = map[int16]string{
	1: "message_id",
}

type WithdrawMessageReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId    int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId     int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	MessageId  int64                        `thrift:"message_id,4" frugal:"4,default,i64" json:"message_id"`
}

func NewWithdrawMessageReq() *WithdrawMessageReq {
	return &WithdrawMessageReq{}
}

func (p *WithdrawMessageReq) InitDefault() {
}

var WithdrawMessageReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *WithdrawMessageReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return WithdrawMessageReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *WithdrawMessageReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *WithdrawMessageReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *WithdrawMessageReq) GetMessageId() (v int64) {
	return p.MessageId
}
func (p *WithdrawMessageReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *WithdrawMessageReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *WithdrawMessageReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *WithdrawMessageReq) SetMessageId(val int64) {
	p.MessageId = val
}

func (p *WithdrawMessageReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *WithdrawMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WithdrawMessageReq(%+v)", *p)
}

var fieldIDToName_WithdrawMessageReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
	4: "message_id",
}

type WithdrawMessageResp struct {
}

func NewWithdrawMessageResp() *WithdrawMessageResp {
	return &WithdrawMessageResp{}
}

func (p *WithdrawMessageResp) InitDefault() {
}

func (p *WithdrawMessageResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WithdrawMessageResp(%+v)", *p)
}

var fieldIDToName_WithdrawMessageResp = map[int16]string{}

type DeleteMessageAllGroupReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId    int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
}

func NewDeleteMessageAllGroupReq() *DeleteMessageAllGroupReq {
	return &DeleteMessageAllGroupReq{}
}

func (p *DeleteMessageAllGroupReq) InitDefault() {
}

var DeleteMessageAllGroupReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *DeleteMessageAllGroupReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return DeleteMessageAllGroupReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *DeleteMessageAllGroupReq) GetGroupId() (v int64) {
	return p.GroupId
}
func (p *DeleteMessageAllGroupReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *DeleteMessageAllGroupReq) SetGroupId(val int64) {
	p.GroupId = val
}

func (p *DeleteMessageAllGroupReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *DeleteMessageAllGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteMessageAllGroupReq(%+v)", *p)
}

var fieldIDToName_DeleteMessageAllGroupReq = map[int16]string{
	1: "common_info",
	2: "group_id",
}

type DeleteMessageAllGroupResp struct {
}

func NewDeleteMessageAllGroupResp() *DeleteMessageAllGroupResp {
	return &DeleteMessageAllGroupResp{}
}

func (p *DeleteMessageAllGroupResp) InitDefault() {
}

func (p *DeleteMessageAllGroupResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteMessageAllGroupResp(%+v)", *p)
}

var fieldIDToName_DeleteMessageAllGroupResp = map[int16]string{}

type GetMessageListReq struct {
	CommonInfo      *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId         int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId          int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	StartTimeSecond int64                        `thrift:"start_time_second,4" frugal:"4,default,i64" json:"start_time_second"`
	EndTimeSecond   int64                        `thrift:"end_time_second,5" frugal:"5,default,i64" json:"end_time_second"`
}

func NewGetMessageListReq() *GetMessageListReq {
	return &GetMessageListReq{}
}

func (p *GetMessageListReq) InitDefault() {
}

var GetMessageListReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetMessageListReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetMessageListReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetMessageListReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *GetMessageListReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetMessageListReq) GetStartTimeSecond() (v int64) {
	return p.StartTimeSecond
}

func (p *GetMessageListReq) GetEndTimeSecond() (v int64) {
	return p.EndTimeSecond
}
func (p *GetMessageListReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetMessageListReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *GetMessageListReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetMessageListReq) SetStartTimeSecond(val int64) {
	p.StartTimeSecond = val
}
func (p *GetMessageListReq) SetEndTimeSecond(val int64) {
	p.EndTimeSecond = val
}

func (p *GetMessageListReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetMessageListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMessageListReq(%+v)", *p)
}

var fieldIDToName_GetMessageListReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
	4: "start_time_second",
	5: "end_time_second",
}

type GetMessageListResp struct {
	MessageInfo []*kitexcommonmodel.KitexMessageInfo `thrift:"message_info,1" frugal:"1,default,list<kitexcommonmodel.KitexMessageInfo>" json:"message_info"`
}

func NewGetMessageListResp() *GetMessageListResp {
	return &GetMessageListResp{}
}

func (p *GetMessageListResp) InitDefault() {
}

func (p *GetMessageListResp) GetMessageInfo() (v []*kitexcommonmodel.KitexMessageInfo) {
	return p.MessageInfo
}
func (p *GetMessageListResp) SetMessageInfo(val []*kitexcommonmodel.KitexMessageInfo) {
	p.MessageInfo = val
}

func (p *GetMessageListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMessageListResp(%+v)", *p)
}

var fieldIDToName_GetMessageListResp = map[int16]string{
	1: "message_info",
}

type GetNewMessageReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId    int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId     int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
}

func NewGetNewMessageReq() *GetNewMessageReq {
	return &GetNewMessageReq{}
}

func (p *GetNewMessageReq) InitDefault() {
}

var GetNewMessageReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetNewMessageReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetNewMessageReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetNewMessageReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *GetNewMessageReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetNewMessageReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetNewMessageReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *GetNewMessageReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetNewMessageReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetNewMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetNewMessageReq(%+v)", *p)
}

var fieldIDToName_GetNewMessageReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
}

type GetNewMessageResp struct {
	MessageId      []int64  `thrift:"message_id,1" frugal:"1,default,list<i64>" json:"message_id"`
	SendTimeSecond []int64  `thrift:"send_time_second,2" frugal:"2,default,list<i64>" json:"send_time_second"`
	MessageType    []string `thrift:"message_type,3" frugal:"3,default,list<string>" json:"message_type"`
	MessageContent []string `thrift:"message_content,4" frugal:"4,default,list<string>" json:"message_content"`
}

func NewGetNewMessageResp() *GetNewMessageResp {
	return &GetNewMessageResp{}
}

func (p *GetNewMessageResp) InitDefault() {
}

func (p *GetNewMessageResp) GetMessageId() (v []int64) {
	return p.MessageId
}

func (p *GetNewMessageResp) GetSendTimeSecond() (v []int64) {
	return p.SendTimeSecond
}

func (p *GetNewMessageResp) GetMessageType() (v []string) {
	return p.MessageType
}

func (p *GetNewMessageResp) GetMessageContent() (v []string) {
	return p.MessageContent
}
func (p *GetNewMessageResp) SetMessageId(val []int64) {
	p.MessageId = val
}
func (p *GetNewMessageResp) SetSendTimeSecond(val []int64) {
	p.SendTimeSecond = val
}
func (p *GetNewMessageResp) SetMessageType(val []string) {
	p.MessageType = val
}
func (p *GetNewMessageResp) SetMessageContent(val []string) {
	p.MessageContent = val
}

func (p *GetNewMessageResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetNewMessageResp(%+v)", *p)
}

var fieldIDToName_GetNewMessageResp = map[int16]string{
	1: "message_id",
	2: "send_time_second",
	3: "message_type",
	4: "message_content",
}

type GetFileContentReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId    int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId     int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	MessageId  int64                        `thrift:"message_id,4" frugal:"4,default,i64" json:"message_id"`
}

func NewGetFileContentReq() *GetFileContentReq {
	return &GetFileContentReq{}
}

func (p *GetFileContentReq) InitDefault() {
}

var GetFileContentReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetFileContentReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetFileContentReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetFileContentReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *GetFileContentReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetFileContentReq) GetMessageId() (v int64) {
	return p.MessageId
}
func (p *GetFileContentReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetFileContentReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *GetFileContentReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetFileContentReq) SetMessageId(val int64) {
	p.MessageId = val
}

func (p *GetFileContentReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetFileContentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFileContentReq(%+v)", *p)
}

var fieldIDToName_GetFileContentReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
	4: "message_id",
}

type GetFileContentResp struct {
	DataStream  []byte `thrift:"data_stream,1" frugal:"1,default,binary" json:"data_stream"`
	ContentType string `thrift:"content_type,2" frugal:"2,default,string" json:"content_type"`
}

func NewGetFileContentResp() *GetFileContentResp {
	return &GetFileContentResp{}
}

func (p *GetFileContentResp) InitDefault() {
}

func (p *GetFileContentResp) GetDataStream() (v []byte) {
	return p.DataStream
}

func (p *GetFileContentResp) GetContentType() (v string) {
	return p.ContentType
}
func (p *GetFileContentResp) SetDataStream(val []byte) {
	p.DataStream = val
}
func (p *GetFileContentResp) SetContentType(val string) {
	p.ContentType = val
}

func (p *GetFileContentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFileContentResp(%+v)", *p)
}

var fieldIDToName_GetFileContentResp = map[int16]string{
	1: "data_stream",
	2: "content_type",
}

type SendGroupNoticeReq struct {
	CommonInfo     *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GroupId        int64                        `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId         int64                        `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	MessageContent string                       `thrift:"message_content,4" frugal:"4,default,string" json:"message_content"`
}

func NewSendGroupNoticeReq() *SendGroupNoticeReq {
	return &SendGroupNoticeReq{}
}

func (p *SendGroupNoticeReq) InitDefault() {
}

var SendGroupNoticeReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *SendGroupNoticeReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return SendGroupNoticeReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *SendGroupNoticeReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *SendGroupNoticeReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SendGroupNoticeReq) GetMessageContent() (v string) {
	return p.MessageContent
}
func (p *SendGroupNoticeReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *SendGroupNoticeReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *SendGroupNoticeReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SendGroupNoticeReq) SetMessageContent(val string) {
	p.MessageContent = val
}

func (p *SendGroupNoticeReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *SendGroupNoticeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendGroupNoticeReq(%+v)", *p)
}

var fieldIDToName_SendGroupNoticeReq = map[int16]string{
	1: "common_info",
	2: "group_id",
	3: "user_id",
	4: "message_content",
}

type SendGroupNoticeResp struct {
}

func NewSendGroupNoticeResp() *SendGroupNoticeResp {
	return &SendGroupNoticeResp{}
}

func (p *SendGroupNoticeResp) InitDefault() {
}

func (p *SendGroupNoticeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendGroupNoticeResp(%+v)", *p)
}

var fieldIDToName_SendGroupNoticeResp = map[int16]string{}

type SetOfflineMessageReq struct {
	CommonInfo          *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GoalUserAndDeviceId []string                     `thrift:"goal_user_and_device_id,2" frugal:"2,default,list<string>" json:"goal_user_and_device_id"`
	JsonData            []byte                       `thrift:"json_data,3" frugal:"3,default,binary" json:"json_data"`
}

func NewSetOfflineMessageReq() *SetOfflineMessageReq {
	return &SetOfflineMessageReq{}
}

func (p *SetOfflineMessageReq) InitDefault() {
}

var SetOfflineMessageReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *SetOfflineMessageReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return SetOfflineMessageReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *SetOfflineMessageReq) GetGoalUserAndDeviceId() (v []string) {
	return p.GoalUserAndDeviceId
}

func (p *SetOfflineMessageReq) GetJsonData() (v []byte) {
	return p.JsonData
}
func (p *SetOfflineMessageReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *SetOfflineMessageReq) SetGoalUserAndDeviceId(val []string) {
	p.GoalUserAndDeviceId = val
}
func (p *SetOfflineMessageReq) SetJsonData(val []byte) {
	p.JsonData = val
}

func (p *SetOfflineMessageReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *SetOfflineMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetOfflineMessageReq(%+v)", *p)
}

var fieldIDToName_SetOfflineMessageReq = map[int16]string{
	1: "common_info",
	2: "goal_user_and_device_id",
	3: "json_data",
}

type SetOfflineMessageResp struct {
}

func NewSetOfflineMessageResp() *SetOfflineMessageResp {
	return &SetOfflineMessageResp{}
}

func (p *SetOfflineMessageResp) InitDefault() {
}

func (p *SetOfflineMessageResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetOfflineMessageResp(%+v)", *p)
}

var fieldIDToName_SetOfflineMessageResp = map[int16]string{}

type GetOfflineMessageListReq struct {
	CommonInfo      *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserAndDeviceId string                       `thrift:"user_and_device_id,2" frugal:"2,default,string" json:"user_and_device_id"`
}

func NewGetOfflineMessageListReq() *GetOfflineMessageListReq {
	return &GetOfflineMessageListReq{}
}

func (p *GetOfflineMessageListReq) InitDefault() {
}

var GetOfflineMessageListReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetOfflineMessageListReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetOfflineMessageListReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetOfflineMessageListReq) GetUserAndDeviceId() (v string) {
	return p.UserAndDeviceId
}
func (p *GetOfflineMessageListReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetOfflineMessageListReq) SetUserAndDeviceId(val string) {
	p.UserAndDeviceId = val
}

func (p *GetOfflineMessageListReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetOfflineMessageListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOfflineMessageListReq(%+v)", *p)
}

var fieldIDToName_GetOfflineMessageListReq = map[int16]string{
	1: "common_info",
	2: "user_and_device_id",
}

type GetOfflineMessageListResp struct {
	JsonData [][]byte `thrift:"json_data,1" frugal:"1,default,list<binary>" json:"json_data"`
	Exist    bool     `thrift:"exist,2" frugal:"2,default,bool" json:"exist"`
}

func NewGetOfflineMessageListResp() *GetOfflineMessageListResp {
	return &GetOfflineMessageListResp{}
}

func (p *GetOfflineMessageListResp) InitDefault() {
}

func (p *GetOfflineMessageListResp) GetJsonData() (v [][]byte) {
	return p.JsonData
}

func (p *GetOfflineMessageListResp) GetExist() (v bool) {
	return p.Exist
}
func (p *GetOfflineMessageListResp) SetJsonData(val [][]byte) {
	p.JsonData = val
}
func (p *GetOfflineMessageListResp) SetExist(val bool) {
	p.Exist = val
}

func (p *GetOfflineMessageListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOfflineMessageListResp(%+v)", *p)
}

var fieldIDToName_GetOfflineMessageListResp = map[int16]string{
	1: "json_data",
	2: "exist",
}

type KitexMessageService interface {
	SendMessage(ctx context.Context, req *SendMessageReq) (r *SendMessageResp, err error)

	SendFile(ctx context.Context, req *SendFileReq) (r *SendFileResp, err error)

	SendVoice(ctx context.Context, req *SendVoiceReq) (r *SendVoiceResp, err error)

	SendPicture(ctx context.Context, req *SendPictureReq) (r *SendPictureResp, err error)

	WithdrawMessage(ctx context.Context, req *WithdrawMessageReq) (r *WithdrawMessageResp, err error)

	DeleteMessageAllGroup(ctx context.Context, req *DeleteMessageAllGroupReq) (r *DeleteMessageAllGroupResp, err error)

	GetMessageList(ctx context.Context, req *GetMessageListReq) (r *GetMessageListResp, err error)

	GetNewMessage(ctx context.Context, req *GetNewMessageReq) (r *GetNewMessageResp, err error)

	GetFileContent(ctx context.Context, req *GetFileContentReq) (r *GetFileContentResp, err error)

	SendGroupNotice(ctx context.Context, req *SendGroupNoticeReq) (r *SendGroupNoticeResp, err error)

	SetOfflineMessage(ctx context.Context, req *SetOfflineMessageReq) (r *SetOfflineMessageResp, err error)

	GetOfflineMessageList(ctx context.Context, req *GetOfflineMessageListReq) (r *GetOfflineMessageListResp, err error)
}

type KitexMessageServiceSendMessageArgs struct {
	Req *SendMessageReq `thrift:"req,1" frugal:"1,default,SendMessageReq" json:"req"`
}

func NewKitexMessageServiceSendMessageArgs() *KitexMessageServiceSendMessageArgs {
	return &KitexMessageServiceSendMessageArgs{}
}

func (p *KitexMessageServiceSendMessageArgs) InitDefault() {
}

var KitexMessageServiceSendMessageArgs_Req_DEFAULT *SendMessageReq

func (p *KitexMessageServiceSendMessageArgs) GetReq() (v *SendMessageReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceSendMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceSendMessageArgs) SetReq(val *SendMessageReq) {
	p.Req = val
}

func (p *KitexMessageServiceSendMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceSendMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendMessageArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendMessageArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceSendMessageResult struct {
	Success *SendMessageResp `thrift:"success,0,optional" frugal:"0,optional,SendMessageResp" json:"success,omitempty"`
}

func NewKitexMessageServiceSendMessageResult() *KitexMessageServiceSendMessageResult {
	return &KitexMessageServiceSendMessageResult{}
}

func (p *KitexMessageServiceSendMessageResult) InitDefault() {
}

var KitexMessageServiceSendMessageResult_Success_DEFAULT *SendMessageResp

func (p *KitexMessageServiceSendMessageResult) GetSuccess() (v *SendMessageResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceSendMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceSendMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendMessageResp)
}

func (p *KitexMessageServiceSendMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceSendMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendMessageResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendMessageResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceSendFileArgs struct {
	Req *SendFileReq `thrift:"req,1" frugal:"1,default,SendFileReq" json:"req"`
}

func NewKitexMessageServiceSendFileArgs() *KitexMessageServiceSendFileArgs {
	return &KitexMessageServiceSendFileArgs{}
}

func (p *KitexMessageServiceSendFileArgs) InitDefault() {
}

var KitexMessageServiceSendFileArgs_Req_DEFAULT *SendFileReq

func (p *KitexMessageServiceSendFileArgs) GetReq() (v *SendFileReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceSendFileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceSendFileArgs) SetReq(val *SendFileReq) {
	p.Req = val
}

func (p *KitexMessageServiceSendFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceSendFileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendFileArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendFileArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceSendFileResult struct {
	Success *SendFileResp `thrift:"success,0,optional" frugal:"0,optional,SendFileResp" json:"success,omitempty"`
}

func NewKitexMessageServiceSendFileResult() *KitexMessageServiceSendFileResult {
	return &KitexMessageServiceSendFileResult{}
}

func (p *KitexMessageServiceSendFileResult) InitDefault() {
}

var KitexMessageServiceSendFileResult_Success_DEFAULT *SendFileResp

func (p *KitexMessageServiceSendFileResult) GetSuccess() (v *SendFileResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceSendFileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceSendFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendFileResp)
}

func (p *KitexMessageServiceSendFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceSendFileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendFileResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendFileResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceSendVoiceArgs struct {
	Req *SendVoiceReq `thrift:"req,1" frugal:"1,default,SendVoiceReq" json:"req"`
}

func NewKitexMessageServiceSendVoiceArgs() *KitexMessageServiceSendVoiceArgs {
	return &KitexMessageServiceSendVoiceArgs{}
}

func (p *KitexMessageServiceSendVoiceArgs) InitDefault() {
}

var KitexMessageServiceSendVoiceArgs_Req_DEFAULT *SendVoiceReq

func (p *KitexMessageServiceSendVoiceArgs) GetReq() (v *SendVoiceReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceSendVoiceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceSendVoiceArgs) SetReq(val *SendVoiceReq) {
	p.Req = val
}

func (p *KitexMessageServiceSendVoiceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceSendVoiceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendVoiceArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendVoiceArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceSendVoiceResult struct {
	Success *SendVoiceResp `thrift:"success,0,optional" frugal:"0,optional,SendVoiceResp" json:"success,omitempty"`
}

func NewKitexMessageServiceSendVoiceResult() *KitexMessageServiceSendVoiceResult {
	return &KitexMessageServiceSendVoiceResult{}
}

func (p *KitexMessageServiceSendVoiceResult) InitDefault() {
}

var KitexMessageServiceSendVoiceResult_Success_DEFAULT *SendVoiceResp

func (p *KitexMessageServiceSendVoiceResult) GetSuccess() (v *SendVoiceResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceSendVoiceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceSendVoiceResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendVoiceResp)
}

func (p *KitexMessageServiceSendVoiceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceSendVoiceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendVoiceResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendVoiceResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceSendPictureArgs struct {
	Req *SendPictureReq `thrift:"req,1" frugal:"1,default,SendPictureReq" json:"req"`
}

func NewKitexMessageServiceSendPictureArgs() *KitexMessageServiceSendPictureArgs {
	return &KitexMessageServiceSendPictureArgs{}
}

func (p *KitexMessageServiceSendPictureArgs) InitDefault() {
}

var KitexMessageServiceSendPictureArgs_Req_DEFAULT *SendPictureReq

func (p *KitexMessageServiceSendPictureArgs) GetReq() (v *SendPictureReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceSendPictureArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceSendPictureArgs) SetReq(val *SendPictureReq) {
	p.Req = val
}

func (p *KitexMessageServiceSendPictureArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceSendPictureArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendPictureArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendPictureArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceSendPictureResult struct {
	Success *SendPictureResp `thrift:"success,0,optional" frugal:"0,optional,SendPictureResp" json:"success,omitempty"`
}

func NewKitexMessageServiceSendPictureResult() *KitexMessageServiceSendPictureResult {
	return &KitexMessageServiceSendPictureResult{}
}

func (p *KitexMessageServiceSendPictureResult) InitDefault() {
}

var KitexMessageServiceSendPictureResult_Success_DEFAULT *SendPictureResp

func (p *KitexMessageServiceSendPictureResult) GetSuccess() (v *SendPictureResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceSendPictureResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceSendPictureResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendPictureResp)
}

func (p *KitexMessageServiceSendPictureResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceSendPictureResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendPictureResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendPictureResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceWithdrawMessageArgs struct {
	Req *WithdrawMessageReq `thrift:"req,1" frugal:"1,default,WithdrawMessageReq" json:"req"`
}

func NewKitexMessageServiceWithdrawMessageArgs() *KitexMessageServiceWithdrawMessageArgs {
	return &KitexMessageServiceWithdrawMessageArgs{}
}

func (p *KitexMessageServiceWithdrawMessageArgs) InitDefault() {
}

var KitexMessageServiceWithdrawMessageArgs_Req_DEFAULT *WithdrawMessageReq

func (p *KitexMessageServiceWithdrawMessageArgs) GetReq() (v *WithdrawMessageReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceWithdrawMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceWithdrawMessageArgs) SetReq(val *WithdrawMessageReq) {
	p.Req = val
}

func (p *KitexMessageServiceWithdrawMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceWithdrawMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceWithdrawMessageArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceWithdrawMessageArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceWithdrawMessageResult struct {
	Success *WithdrawMessageResp `thrift:"success,0,optional" frugal:"0,optional,WithdrawMessageResp" json:"success,omitempty"`
}

func NewKitexMessageServiceWithdrawMessageResult() *KitexMessageServiceWithdrawMessageResult {
	return &KitexMessageServiceWithdrawMessageResult{}
}

func (p *KitexMessageServiceWithdrawMessageResult) InitDefault() {
}

var KitexMessageServiceWithdrawMessageResult_Success_DEFAULT *WithdrawMessageResp

func (p *KitexMessageServiceWithdrawMessageResult) GetSuccess() (v *WithdrawMessageResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceWithdrawMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceWithdrawMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*WithdrawMessageResp)
}

func (p *KitexMessageServiceWithdrawMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceWithdrawMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceWithdrawMessageResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceWithdrawMessageResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceDeleteMessageAllGroupArgs struct {
	Req *DeleteMessageAllGroupReq `thrift:"req,1" frugal:"1,default,DeleteMessageAllGroupReq" json:"req"`
}

func NewKitexMessageServiceDeleteMessageAllGroupArgs() *KitexMessageServiceDeleteMessageAllGroupArgs {
	return &KitexMessageServiceDeleteMessageAllGroupArgs{}
}

func (p *KitexMessageServiceDeleteMessageAllGroupArgs) InitDefault() {
}

var KitexMessageServiceDeleteMessageAllGroupArgs_Req_DEFAULT *DeleteMessageAllGroupReq

func (p *KitexMessageServiceDeleteMessageAllGroupArgs) GetReq() (v *DeleteMessageAllGroupReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceDeleteMessageAllGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceDeleteMessageAllGroupArgs) SetReq(val *DeleteMessageAllGroupReq) {
	p.Req = val
}

func (p *KitexMessageServiceDeleteMessageAllGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceDeleteMessageAllGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceDeleteMessageAllGroupArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceDeleteMessageAllGroupArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceDeleteMessageAllGroupResult struct {
	Success *DeleteMessageAllGroupResp `thrift:"success,0,optional" frugal:"0,optional,DeleteMessageAllGroupResp" json:"success,omitempty"`
}

func NewKitexMessageServiceDeleteMessageAllGroupResult() *KitexMessageServiceDeleteMessageAllGroupResult {
	return &KitexMessageServiceDeleteMessageAllGroupResult{}
}

func (p *KitexMessageServiceDeleteMessageAllGroupResult) InitDefault() {
}

var KitexMessageServiceDeleteMessageAllGroupResult_Success_DEFAULT *DeleteMessageAllGroupResp

func (p *KitexMessageServiceDeleteMessageAllGroupResult) GetSuccess() (v *DeleteMessageAllGroupResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceDeleteMessageAllGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceDeleteMessageAllGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteMessageAllGroupResp)
}

func (p *KitexMessageServiceDeleteMessageAllGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceDeleteMessageAllGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceDeleteMessageAllGroupResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceDeleteMessageAllGroupResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceGetMessageListArgs struct {
	Req *GetMessageListReq `thrift:"req,1" frugal:"1,default,GetMessageListReq" json:"req"`
}

func NewKitexMessageServiceGetMessageListArgs() *KitexMessageServiceGetMessageListArgs {
	return &KitexMessageServiceGetMessageListArgs{}
}

func (p *KitexMessageServiceGetMessageListArgs) InitDefault() {
}

var KitexMessageServiceGetMessageListArgs_Req_DEFAULT *GetMessageListReq

func (p *KitexMessageServiceGetMessageListArgs) GetReq() (v *GetMessageListReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceGetMessageListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceGetMessageListArgs) SetReq(val *GetMessageListReq) {
	p.Req = val
}

func (p *KitexMessageServiceGetMessageListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceGetMessageListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceGetMessageListArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceGetMessageListArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceGetMessageListResult struct {
	Success *GetMessageListResp `thrift:"success,0,optional" frugal:"0,optional,GetMessageListResp" json:"success,omitempty"`
}

func NewKitexMessageServiceGetMessageListResult() *KitexMessageServiceGetMessageListResult {
	return &KitexMessageServiceGetMessageListResult{}
}

func (p *KitexMessageServiceGetMessageListResult) InitDefault() {
}

var KitexMessageServiceGetMessageListResult_Success_DEFAULT *GetMessageListResp

func (p *KitexMessageServiceGetMessageListResult) GetSuccess() (v *GetMessageListResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceGetMessageListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceGetMessageListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetMessageListResp)
}

func (p *KitexMessageServiceGetMessageListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceGetMessageListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceGetMessageListResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceGetMessageListResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceGetNewMessageArgs struct {
	Req *GetNewMessageReq `thrift:"req,1" frugal:"1,default,GetNewMessageReq" json:"req"`
}

func NewKitexMessageServiceGetNewMessageArgs() *KitexMessageServiceGetNewMessageArgs {
	return &KitexMessageServiceGetNewMessageArgs{}
}

func (p *KitexMessageServiceGetNewMessageArgs) InitDefault() {
}

var KitexMessageServiceGetNewMessageArgs_Req_DEFAULT *GetNewMessageReq

func (p *KitexMessageServiceGetNewMessageArgs) GetReq() (v *GetNewMessageReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceGetNewMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceGetNewMessageArgs) SetReq(val *GetNewMessageReq) {
	p.Req = val
}

func (p *KitexMessageServiceGetNewMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceGetNewMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceGetNewMessageArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceGetNewMessageArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceGetNewMessageResult struct {
	Success *GetNewMessageResp `thrift:"success,0,optional" frugal:"0,optional,GetNewMessageResp" json:"success,omitempty"`
}

func NewKitexMessageServiceGetNewMessageResult() *KitexMessageServiceGetNewMessageResult {
	return &KitexMessageServiceGetNewMessageResult{}
}

func (p *KitexMessageServiceGetNewMessageResult) InitDefault() {
}

var KitexMessageServiceGetNewMessageResult_Success_DEFAULT *GetNewMessageResp

func (p *KitexMessageServiceGetNewMessageResult) GetSuccess() (v *GetNewMessageResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceGetNewMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceGetNewMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetNewMessageResp)
}

func (p *KitexMessageServiceGetNewMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceGetNewMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceGetNewMessageResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceGetNewMessageResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceGetFileContentArgs struct {
	Req *GetFileContentReq `thrift:"req,1" frugal:"1,default,GetFileContentReq" json:"req"`
}

func NewKitexMessageServiceGetFileContentArgs() *KitexMessageServiceGetFileContentArgs {
	return &KitexMessageServiceGetFileContentArgs{}
}

func (p *KitexMessageServiceGetFileContentArgs) InitDefault() {
}

var KitexMessageServiceGetFileContentArgs_Req_DEFAULT *GetFileContentReq

func (p *KitexMessageServiceGetFileContentArgs) GetReq() (v *GetFileContentReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceGetFileContentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceGetFileContentArgs) SetReq(val *GetFileContentReq) {
	p.Req = val
}

func (p *KitexMessageServiceGetFileContentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceGetFileContentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceGetFileContentArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceGetFileContentArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceGetFileContentResult struct {
	Success *GetFileContentResp `thrift:"success,0,optional" frugal:"0,optional,GetFileContentResp" json:"success,omitempty"`
}

func NewKitexMessageServiceGetFileContentResult() *KitexMessageServiceGetFileContentResult {
	return &KitexMessageServiceGetFileContentResult{}
}

func (p *KitexMessageServiceGetFileContentResult) InitDefault() {
}

var KitexMessageServiceGetFileContentResult_Success_DEFAULT *GetFileContentResp

func (p *KitexMessageServiceGetFileContentResult) GetSuccess() (v *GetFileContentResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceGetFileContentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceGetFileContentResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFileContentResp)
}

func (p *KitexMessageServiceGetFileContentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceGetFileContentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceGetFileContentResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceGetFileContentResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceSendGroupNoticeArgs struct {
	Req *SendGroupNoticeReq `thrift:"req,1" frugal:"1,default,SendGroupNoticeReq" json:"req"`
}

func NewKitexMessageServiceSendGroupNoticeArgs() *KitexMessageServiceSendGroupNoticeArgs {
	return &KitexMessageServiceSendGroupNoticeArgs{}
}

func (p *KitexMessageServiceSendGroupNoticeArgs) InitDefault() {
}

var KitexMessageServiceSendGroupNoticeArgs_Req_DEFAULT *SendGroupNoticeReq

func (p *KitexMessageServiceSendGroupNoticeArgs) GetReq() (v *SendGroupNoticeReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceSendGroupNoticeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceSendGroupNoticeArgs) SetReq(val *SendGroupNoticeReq) {
	p.Req = val
}

func (p *KitexMessageServiceSendGroupNoticeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceSendGroupNoticeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendGroupNoticeArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendGroupNoticeArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceSendGroupNoticeResult struct {
	Success *SendGroupNoticeResp `thrift:"success,0,optional" frugal:"0,optional,SendGroupNoticeResp" json:"success,omitempty"`
}

func NewKitexMessageServiceSendGroupNoticeResult() *KitexMessageServiceSendGroupNoticeResult {
	return &KitexMessageServiceSendGroupNoticeResult{}
}

func (p *KitexMessageServiceSendGroupNoticeResult) InitDefault() {
}

var KitexMessageServiceSendGroupNoticeResult_Success_DEFAULT *SendGroupNoticeResp

func (p *KitexMessageServiceSendGroupNoticeResult) GetSuccess() (v *SendGroupNoticeResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceSendGroupNoticeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceSendGroupNoticeResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendGroupNoticeResp)
}

func (p *KitexMessageServiceSendGroupNoticeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceSendGroupNoticeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSendGroupNoticeResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSendGroupNoticeResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceSetOfflineMessageArgs struct {
	Req *SetOfflineMessageReq `thrift:"req,1" frugal:"1,default,SetOfflineMessageReq" json:"req"`
}

func NewKitexMessageServiceSetOfflineMessageArgs() *KitexMessageServiceSetOfflineMessageArgs {
	return &KitexMessageServiceSetOfflineMessageArgs{}
}

func (p *KitexMessageServiceSetOfflineMessageArgs) InitDefault() {
}

var KitexMessageServiceSetOfflineMessageArgs_Req_DEFAULT *SetOfflineMessageReq

func (p *KitexMessageServiceSetOfflineMessageArgs) GetReq() (v *SetOfflineMessageReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceSetOfflineMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceSetOfflineMessageArgs) SetReq(val *SetOfflineMessageReq) {
	p.Req = val
}

func (p *KitexMessageServiceSetOfflineMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceSetOfflineMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSetOfflineMessageArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSetOfflineMessageArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceSetOfflineMessageResult struct {
	Success *SetOfflineMessageResp `thrift:"success,0,optional" frugal:"0,optional,SetOfflineMessageResp" json:"success,omitempty"`
}

func NewKitexMessageServiceSetOfflineMessageResult() *KitexMessageServiceSetOfflineMessageResult {
	return &KitexMessageServiceSetOfflineMessageResult{}
}

func (p *KitexMessageServiceSetOfflineMessageResult) InitDefault() {
}

var KitexMessageServiceSetOfflineMessageResult_Success_DEFAULT *SetOfflineMessageResp

func (p *KitexMessageServiceSetOfflineMessageResult) GetSuccess() (v *SetOfflineMessageResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceSetOfflineMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceSetOfflineMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*SetOfflineMessageResp)
}

func (p *KitexMessageServiceSetOfflineMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceSetOfflineMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceSetOfflineMessageResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceSetOfflineMessageResult = map[int16]string{
	0: "success",
}

type KitexMessageServiceGetOfflineMessageListArgs struct {
	Req *GetOfflineMessageListReq `thrift:"req,1" frugal:"1,default,GetOfflineMessageListReq" json:"req"`
}

func NewKitexMessageServiceGetOfflineMessageListArgs() *KitexMessageServiceGetOfflineMessageListArgs {
	return &KitexMessageServiceGetOfflineMessageListArgs{}
}

func (p *KitexMessageServiceGetOfflineMessageListArgs) InitDefault() {
}

var KitexMessageServiceGetOfflineMessageListArgs_Req_DEFAULT *GetOfflineMessageListReq

func (p *KitexMessageServiceGetOfflineMessageListArgs) GetReq() (v *GetOfflineMessageListReq) {
	if !p.IsSetReq() {
		return KitexMessageServiceGetOfflineMessageListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KitexMessageServiceGetOfflineMessageListArgs) SetReq(val *GetOfflineMessageListReq) {
	p.Req = val
}

func (p *KitexMessageServiceGetOfflineMessageListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KitexMessageServiceGetOfflineMessageListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceGetOfflineMessageListArgs(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceGetOfflineMessageListArgs = map[int16]string{
	1: "req",
}

type KitexMessageServiceGetOfflineMessageListResult struct {
	Success *GetOfflineMessageListResp `thrift:"success,0,optional" frugal:"0,optional,GetOfflineMessageListResp" json:"success,omitempty"`
}

func NewKitexMessageServiceGetOfflineMessageListResult() *KitexMessageServiceGetOfflineMessageListResult {
	return &KitexMessageServiceGetOfflineMessageListResult{}
}

func (p *KitexMessageServiceGetOfflineMessageListResult) InitDefault() {
}

var KitexMessageServiceGetOfflineMessageListResult_Success_DEFAULT *GetOfflineMessageListResp

func (p *KitexMessageServiceGetOfflineMessageListResult) GetSuccess() (v *GetOfflineMessageListResp) {
	if !p.IsSetSuccess() {
		return KitexMessageServiceGetOfflineMessageListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KitexMessageServiceGetOfflineMessageListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOfflineMessageListResp)
}

func (p *KitexMessageServiceGetOfflineMessageListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KitexMessageServiceGetOfflineMessageListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageServiceGetOfflineMessageListResult(%+v)", *p)
}

var fieldIDToName_KitexMessageServiceGetOfflineMessageListResult = map[int16]string{
	0: "success",
}
