// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexaiservice

import (
	kitexaiservice "aim/kitex_gen/kitexaiservice"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendMessageToAi": kitex.NewMethodInfo(
		sendMessageToAiHandler,
		newKitexAiServiceSendMessageToAiArgs,
		newKitexAiServiceSendMessageToAiResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteChatContext": kitex.NewMethodInfo(
		deleteChatContextHandler,
		newKitexAiServiceDeleteChatContextArgs,
		newKitexAiServiceDeleteChatContextResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAiConfig": kitex.NewMethodInfo(
		getAiConfigHandler,
		newKitexAiServiceGetAiConfigArgs,
		newKitexAiServiceGetAiConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAiConfig": kitex.NewMethodInfo(
		updateAiConfigHandler,
		newKitexAiServiceUpdateAiConfigArgs,
		newKitexAiServiceUpdateAiConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAiConfig": kitex.NewMethodInfo(
		deleteAiConfigHandler,
		newKitexAiServiceDeleteAiConfigArgs,
		newKitexAiServiceDeleteAiConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	kitexAiServiceServiceInfo                = NewServiceInfo()
	kitexAiServiceServiceInfoForClient       = NewServiceInfoForClient()
	kitexAiServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return kitexAiServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return kitexAiServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return kitexAiServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KitexAiService"
	handlerType := (*kitexaiservice.KitexAiService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kitexaiservice",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func sendMessageToAiHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexaiservice.KitexAiServiceSendMessageToAiArgs)
	realResult := result.(*kitexaiservice.KitexAiServiceSendMessageToAiResult)
	success, err := handler.(kitexaiservice.KitexAiService).SendMessageToAi(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexAiServiceSendMessageToAiArgs() interface{} {
	return kitexaiservice.NewKitexAiServiceSendMessageToAiArgs()
}

func newKitexAiServiceSendMessageToAiResult() interface{} {
	return kitexaiservice.NewKitexAiServiceSendMessageToAiResult()
}

func deleteChatContextHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexaiservice.KitexAiServiceDeleteChatContextArgs)
	realResult := result.(*kitexaiservice.KitexAiServiceDeleteChatContextResult)
	success, err := handler.(kitexaiservice.KitexAiService).DeleteChatContext(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexAiServiceDeleteChatContextArgs() interface{} {
	return kitexaiservice.NewKitexAiServiceDeleteChatContextArgs()
}

func newKitexAiServiceDeleteChatContextResult() interface{} {
	return kitexaiservice.NewKitexAiServiceDeleteChatContextResult()
}

func getAiConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexaiservice.KitexAiServiceGetAiConfigArgs)
	realResult := result.(*kitexaiservice.KitexAiServiceGetAiConfigResult)
	success, err := handler.(kitexaiservice.KitexAiService).GetAiConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexAiServiceGetAiConfigArgs() interface{} {
	return kitexaiservice.NewKitexAiServiceGetAiConfigArgs()
}

func newKitexAiServiceGetAiConfigResult() interface{} {
	return kitexaiservice.NewKitexAiServiceGetAiConfigResult()
}

func updateAiConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexaiservice.KitexAiServiceUpdateAiConfigArgs)
	realResult := result.(*kitexaiservice.KitexAiServiceUpdateAiConfigResult)
	success, err := handler.(kitexaiservice.KitexAiService).UpdateAiConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexAiServiceUpdateAiConfigArgs() interface{} {
	return kitexaiservice.NewKitexAiServiceUpdateAiConfigArgs()
}

func newKitexAiServiceUpdateAiConfigResult() interface{} {
	return kitexaiservice.NewKitexAiServiceUpdateAiConfigResult()
}

func deleteAiConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexaiservice.KitexAiServiceDeleteAiConfigArgs)
	realResult := result.(*kitexaiservice.KitexAiServiceDeleteAiConfigResult)
	success, err := handler.(kitexaiservice.KitexAiService).DeleteAiConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexAiServiceDeleteAiConfigArgs() interface{} {
	return kitexaiservice.NewKitexAiServiceDeleteAiConfigArgs()
}

func newKitexAiServiceDeleteAiConfigResult() interface{} {
	return kitexaiservice.NewKitexAiServiceDeleteAiConfigResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendMessageToAi(ctx context.Context, req *kitexaiservice.SendMessageToAiReq) (r *kitexaiservice.SendMessageToAiResp, err error) {
	var _args kitexaiservice.KitexAiServiceSendMessageToAiArgs
	_args.Req = req
	var _result kitexaiservice.KitexAiServiceSendMessageToAiResult
	if err = p.c.Call(ctx, "SendMessageToAi", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteChatContext(ctx context.Context, req *kitexaiservice.DeleteChatContextReq) (r *kitexaiservice.DeleteChatContextResp, err error) {
	var _args kitexaiservice.KitexAiServiceDeleteChatContextArgs
	_args.Req = req
	var _result kitexaiservice.KitexAiServiceDeleteChatContextResult
	if err = p.c.Call(ctx, "DeleteChatContext", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAiConfig(ctx context.Context, req *kitexaiservice.GetAiConfigReq) (r *kitexaiservice.GetAiConfigResp, err error) {
	var _args kitexaiservice.KitexAiServiceGetAiConfigArgs
	_args.Req = req
	var _result kitexaiservice.KitexAiServiceGetAiConfigResult
	if err = p.c.Call(ctx, "GetAiConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAiConfig(ctx context.Context, req *kitexaiservice.UpdateAiConfigReq) (r *kitexaiservice.UpdateAiConfigResp, err error) {
	var _args kitexaiservice.KitexAiServiceUpdateAiConfigArgs
	_args.Req = req
	var _result kitexaiservice.KitexAiServiceUpdateAiConfigResult
	if err = p.c.Call(ctx, "UpdateAiConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAiConfig(ctx context.Context, req *kitexaiservice.DeleteAiConfigReq) (r *kitexaiservice.DeleteAiConfigResp, err error) {
	var _args kitexaiservice.KitexAiServiceDeleteAiConfigArgs
	_args.Req = req
	var _result kitexaiservice.KitexAiServiceDeleteAiConfigResult
	if err = p.c.Call(ctx, "DeleteAiConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
