common_config:
  service: "group-service"
  equip_id: 3
  service_info:
    message_service:
      kitex_time_out: 5s
    user_service:
      kitex_time_out: 5s
  nacos_config:
    host: "127.0.0.1"
    port: 8848


service_config:
  timeout: 10s
  service_addr:
    host: "127.0.0.1"
    port: 8890

group_config:
  max_group_name_length: 50
  max_group_nick_name_length: 50
  max_group_mute_time: 168h
  max_group_mute_reason_length: 200

kafka_config:
  broker:
    - "127.0.0.1:9092"

mysql_config:
  username: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  dbname: "aim_group"
  set_max_idle_conns: 10
  set_max_open_conns: 100
  set_conn_max_lifetime: 3600s
  timeout: 10s
  read_timeout: 30s
  write_timeout: 30s

redis_config:
  addr: "127.0.0.1:6379"
  password: "123456"
  pool_size: 100
  min_idle_conns: 10
  max_idle_conns: 50
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  conn_max_lifetime: 3600s
  conn_max_idle_time: 600s