// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexgroupservice

import (
	kitexgroupservice "aim/kitex_gen/kitexgroupservice"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetGroupInfo(ctx context.Context, req *kitexgroupservice.GetGroupInfoReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupInfoResp, err error)
	ChangeGroupInfo(ctx context.Context, req *kitexgroupservice.ChangeGroupInfoReq, callOptions ...callopt.Option) (r *kitexgroupservice.ChangeGroupInfoResp, err error)
	SearchGroup(ctx context.Context, req *kitexgroupservice.SearchGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.SearchGroupResp, err error)
	CreateGroup(ctx context.Context, req *kitexgroupservice.CreateGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.CreateGroupResp, err error)
	DeleteGroup(ctx context.Context, req *kitexgroupservice.DeleteGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.DeleteGroupResp, err error)
	LeaveGroup(ctx context.Context, req *kitexgroupservice.LeaveGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.LeaveGroupResp, err error)
	SetGroupApply(ctx context.Context, req *kitexgroupservice.SetGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservice.SetGroupApplyResp, err error)
	GetGroupApplyList(ctx context.Context, req *kitexgroupservice.GetGroupApplyListReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupApplyListResp, err error)
	GetLastVisitTime(ctx context.Context, req *kitexgroupservice.GetLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetLastVisitTimeResp, err error)
	AgreeGroupApply(ctx context.Context, req *kitexgroupservice.AgreeGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservice.AgreeGroupApplyResp, err error)
	RefuseGroupApply(ctx context.Context, req *kitexgroupservice.RefuseGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservice.RefuseGroupApplyResp, err error)
	TransformGroupOwner(ctx context.Context, req *kitexgroupservice.TransformGroupOwnerReq, callOptions ...callopt.Option) (r *kitexgroupservice.TransformGroupOwnerResp, err error)
	KickOutGroup(ctx context.Context, req *kitexgroupservice.KickOutGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.KickOutGroupResp, err error)
	SetManager(ctx context.Context, req *kitexgroupservice.SetManagerReq, callOptions ...callopt.Option) (r *kitexgroupservice.SetManagerResp, err error)
	RevokeManager(ctx context.Context, req *kitexgroupservice.RevokeManagerReq, callOptions ...callopt.Option) (r *kitexgroupservice.RevokeManagerResp, err error)
	GetGroupInfoWithUser(ctx context.Context, req *kitexgroupservice.GetGroupInfoWithUserReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupInfoWithUserResp, err error)
	UpdateGroupInfoWithUser(ctx context.Context, req *kitexgroupservice.UpdateGroupInfoWithUserReq, callOptions ...callopt.Option) (r *kitexgroupservice.UpdateGroupInfoWithUserResp, err error)
	CreatSession(ctx context.Context, req *kitexgroupservice.CreatSessionReq, callOptions ...callopt.Option) (r *kitexgroupservice.CreatSessionResp, err error)
	DeleteSession(ctx context.Context, req *kitexgroupservice.DeleteSessionReq, callOptions ...callopt.Option) (r *kitexgroupservice.DeleteSessionResp, err error)
	GetFriendLastVisitTime(ctx context.Context, req *kitexgroupservice.GetFriendLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetFriendLastVisitTimeResp, err error)
	ApplyForFriend(ctx context.Context, req *kitexgroupservice.ApplyForFriendReq, callOptions ...callopt.Option) (r *kitexgroupservice.ApplyForFriendResp, err error)
	GetFriendApplyList(ctx context.Context, req *kitexgroupservice.GetFriendApplyListReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetFriendApplyListResp, err error)
	RefuseFriendApply(ctx context.Context, req *kitexgroupservice.RefuseFriendApplyReq, callOptions ...callopt.Option) (r *kitexgroupservice.RefuseFriendApplyResp, err error)
	GetGroupAndSessionID(ctx context.Context, req *kitexgroupservice.GetGroupAndSessionIDReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupAndSessionIDResp, err error)
	GetGroupOrSessionRoleAndExist(ctx context.Context, req *kitexgroupservice.GetGroupOrSessionRoleAndExistReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupOrSessionRoleAndExistResp, err error)
	SetLastVisitTime(ctx context.Context, req *kitexgroupservice.SetLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservice.SetLastVisitTimeResp, err error)
	GetGroupUserID(ctx context.Context, req *kitexgroupservice.GetGroupUserIDReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupUserIDResp, err error)
	SetMute(ctx context.Context, req *kitexgroupservice.SetMuteReq, callOptions ...callopt.Option) (r *kitexgroupservice.SetMuteResp, err error)
	ReleaseMute(ctx context.Context, req *kitexgroupservice.ReleaseMuteReq, callOptions ...callopt.Option) (r *kitexgroupservice.ReleaseMuteResp, err error)
	GetMuteStatus(ctx context.Context, req *kitexgroupservice.GetMuteStatusReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetMuteStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKitexGroupServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKitexGroupServiceClient struct {
	*kClient
}

func (p *kKitexGroupServiceClient) GetGroupInfo(ctx context.Context, req *kitexgroupservice.GetGroupInfoReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupInfo(ctx, req)
}

func (p *kKitexGroupServiceClient) ChangeGroupInfo(ctx context.Context, req *kitexgroupservice.ChangeGroupInfoReq, callOptions ...callopt.Option) (r *kitexgroupservice.ChangeGroupInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeGroupInfo(ctx, req)
}

func (p *kKitexGroupServiceClient) SearchGroup(ctx context.Context, req *kitexgroupservice.SearchGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.SearchGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchGroup(ctx, req)
}

func (p *kKitexGroupServiceClient) CreateGroup(ctx context.Context, req *kitexgroupservice.CreateGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.CreateGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateGroup(ctx, req)
}

func (p *kKitexGroupServiceClient) DeleteGroup(ctx context.Context, req *kitexgroupservice.DeleteGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.DeleteGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteGroup(ctx, req)
}

func (p *kKitexGroupServiceClient) LeaveGroup(ctx context.Context, req *kitexgroupservice.LeaveGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.LeaveGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LeaveGroup(ctx, req)
}

func (p *kKitexGroupServiceClient) SetGroupApply(ctx context.Context, req *kitexgroupservice.SetGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservice.SetGroupApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetGroupApply(ctx, req)
}

func (p *kKitexGroupServiceClient) GetGroupApplyList(ctx context.Context, req *kitexgroupservice.GetGroupApplyListReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupApplyListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupApplyList(ctx, req)
}

func (p *kKitexGroupServiceClient) GetLastVisitTime(ctx context.Context, req *kitexgroupservice.GetLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetLastVisitTimeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLastVisitTime(ctx, req)
}

func (p *kKitexGroupServiceClient) AgreeGroupApply(ctx context.Context, req *kitexgroupservice.AgreeGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservice.AgreeGroupApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AgreeGroupApply(ctx, req)
}

func (p *kKitexGroupServiceClient) RefuseGroupApply(ctx context.Context, req *kitexgroupservice.RefuseGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservice.RefuseGroupApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefuseGroupApply(ctx, req)
}

func (p *kKitexGroupServiceClient) TransformGroupOwner(ctx context.Context, req *kitexgroupservice.TransformGroupOwnerReq, callOptions ...callopt.Option) (r *kitexgroupservice.TransformGroupOwnerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TransformGroupOwner(ctx, req)
}

func (p *kKitexGroupServiceClient) KickOutGroup(ctx context.Context, req *kitexgroupservice.KickOutGroupReq, callOptions ...callopt.Option) (r *kitexgroupservice.KickOutGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.KickOutGroup(ctx, req)
}

func (p *kKitexGroupServiceClient) SetManager(ctx context.Context, req *kitexgroupservice.SetManagerReq, callOptions ...callopt.Option) (r *kitexgroupservice.SetManagerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetManager(ctx, req)
}

func (p *kKitexGroupServiceClient) RevokeManager(ctx context.Context, req *kitexgroupservice.RevokeManagerReq, callOptions ...callopt.Option) (r *kitexgroupservice.RevokeManagerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeManager(ctx, req)
}

func (p *kKitexGroupServiceClient) GetGroupInfoWithUser(ctx context.Context, req *kitexgroupservice.GetGroupInfoWithUserReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupInfoWithUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupInfoWithUser(ctx, req)
}

func (p *kKitexGroupServiceClient) UpdateGroupInfoWithUser(ctx context.Context, req *kitexgroupservice.UpdateGroupInfoWithUserReq, callOptions ...callopt.Option) (r *kitexgroupservice.UpdateGroupInfoWithUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateGroupInfoWithUser(ctx, req)
}

func (p *kKitexGroupServiceClient) CreatSession(ctx context.Context, req *kitexgroupservice.CreatSessionReq, callOptions ...callopt.Option) (r *kitexgroupservice.CreatSessionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatSession(ctx, req)
}

func (p *kKitexGroupServiceClient) DeleteSession(ctx context.Context, req *kitexgroupservice.DeleteSessionReq, callOptions ...callopt.Option) (r *kitexgroupservice.DeleteSessionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteSession(ctx, req)
}

func (p *kKitexGroupServiceClient) GetFriendLastVisitTime(ctx context.Context, req *kitexgroupservice.GetFriendLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetFriendLastVisitTimeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendLastVisitTime(ctx, req)
}

func (p *kKitexGroupServiceClient) ApplyForFriend(ctx context.Context, req *kitexgroupservice.ApplyForFriendReq, callOptions ...callopt.Option) (r *kitexgroupservice.ApplyForFriendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplyForFriend(ctx, req)
}

func (p *kKitexGroupServiceClient) GetFriendApplyList(ctx context.Context, req *kitexgroupservice.GetFriendApplyListReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetFriendApplyListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendApplyList(ctx, req)
}

func (p *kKitexGroupServiceClient) RefuseFriendApply(ctx context.Context, req *kitexgroupservice.RefuseFriendApplyReq, callOptions ...callopt.Option) (r *kitexgroupservice.RefuseFriendApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefuseFriendApply(ctx, req)
}

func (p *kKitexGroupServiceClient) GetGroupAndSessionID(ctx context.Context, req *kitexgroupservice.GetGroupAndSessionIDReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupAndSessionIDResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupAndSessionID(ctx, req)
}

func (p *kKitexGroupServiceClient) GetGroupOrSessionRoleAndExist(ctx context.Context, req *kitexgroupservice.GetGroupOrSessionRoleAndExistReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupOrSessionRoleAndExistResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupOrSessionRoleAndExist(ctx, req)
}

func (p *kKitexGroupServiceClient) SetLastVisitTime(ctx context.Context, req *kitexgroupservice.SetLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservice.SetLastVisitTimeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetLastVisitTime(ctx, req)
}

func (p *kKitexGroupServiceClient) GetGroupUserID(ctx context.Context, req *kitexgroupservice.GetGroupUserIDReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetGroupUserIDResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupUserID(ctx, req)
}

func (p *kKitexGroupServiceClient) SetMute(ctx context.Context, req *kitexgroupservice.SetMuteReq, callOptions ...callopt.Option) (r *kitexgroupservice.SetMuteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetMute(ctx, req)
}

func (p *kKitexGroupServiceClient) ReleaseMute(ctx context.Context, req *kitexgroupservice.ReleaseMuteReq, callOptions ...callopt.Option) (r *kitexgroupservice.ReleaseMuteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseMute(ctx, req)
}

func (p *kKitexGroupServiceClient) GetMuteStatus(ctx context.Context, req *kitexgroupservice.GetMuteStatusReq, callOptions ...callopt.Option) (r *kitexgroupservice.GetMuteStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMuteStatus(ctx, req)
}
