// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexgroupservice

import (
	kitexgroupservice "aim/kitex_gen/kitexgroupservice"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetGroupInfo": kitex.NewMethodInfo(
		getGroupInfoHandler,
		newKitexGroupServiceGetGroupInfoArgs,
		newKitexGroupServiceGetGroupInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeGroupInfo": kitex.NewMethodInfo(
		changeGroupInfoHandler,
		newKitexGroupServiceChangeGroupInfoArgs,
		newKitexGroupServiceChangeGroupInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchGroup": kitex.NewMethodInfo(
		searchGroupHandler,
		newKitexGroupServiceSearchGroupArgs,
		newKitexGroupServiceSearchGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateGroup": kitex.NewMethodInfo(
		createGroupHandler,
		newKitexGroupServiceCreateGroupArgs,
		newKitexGroupServiceCreateGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteGroup": kitex.NewMethodInfo(
		deleteGroupHandler,
		newKitexGroupServiceDeleteGroupArgs,
		newKitexGroupServiceDeleteGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LeaveGroup": kitex.NewMethodInfo(
		leaveGroupHandler,
		newKitexGroupServiceLeaveGroupArgs,
		newKitexGroupServiceLeaveGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetGroupApply": kitex.NewMethodInfo(
		setGroupApplyHandler,
		newKitexGroupServiceSetGroupApplyArgs,
		newKitexGroupServiceSetGroupApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupApplyList": kitex.NewMethodInfo(
		getGroupApplyListHandler,
		newKitexGroupServiceGetGroupApplyListArgs,
		newKitexGroupServiceGetGroupApplyListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLastVisitTime": kitex.NewMethodInfo(
		getLastVisitTimeHandler,
		newKitexGroupServiceGetLastVisitTimeArgs,
		newKitexGroupServiceGetLastVisitTimeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AgreeGroupApply": kitex.NewMethodInfo(
		agreeGroupApplyHandler,
		newKitexGroupServiceAgreeGroupApplyArgs,
		newKitexGroupServiceAgreeGroupApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefuseGroupApply": kitex.NewMethodInfo(
		refuseGroupApplyHandler,
		newKitexGroupServiceRefuseGroupApplyArgs,
		newKitexGroupServiceRefuseGroupApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TransformGroupOwner": kitex.NewMethodInfo(
		transformGroupOwnerHandler,
		newKitexGroupServiceTransformGroupOwnerArgs,
		newKitexGroupServiceTransformGroupOwnerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"KickOutGroup": kitex.NewMethodInfo(
		kickOutGroupHandler,
		newKitexGroupServiceKickOutGroupArgs,
		newKitexGroupServiceKickOutGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetManager": kitex.NewMethodInfo(
		setManagerHandler,
		newKitexGroupServiceSetManagerArgs,
		newKitexGroupServiceSetManagerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RevokeManager": kitex.NewMethodInfo(
		revokeManagerHandler,
		newKitexGroupServiceRevokeManagerArgs,
		newKitexGroupServiceRevokeManagerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupInfoWithUser": kitex.NewMethodInfo(
		getGroupInfoWithUserHandler,
		newKitexGroupServiceGetGroupInfoWithUserArgs,
		newKitexGroupServiceGetGroupInfoWithUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateGroupInfoWithUser": kitex.NewMethodInfo(
		updateGroupInfoWithUserHandler,
		newKitexGroupServiceUpdateGroupInfoWithUserArgs,
		newKitexGroupServiceUpdateGroupInfoWithUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreatSession": kitex.NewMethodInfo(
		creatSessionHandler,
		newKitexGroupServiceCreatSessionArgs,
		newKitexGroupServiceCreatSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteSession": kitex.NewMethodInfo(
		deleteSessionHandler,
		newKitexGroupServiceDeleteSessionArgs,
		newKitexGroupServiceDeleteSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendLastVisitTime": kitex.NewMethodInfo(
		getFriendLastVisitTimeHandler,
		newKitexGroupServiceGetFriendLastVisitTimeArgs,
		newKitexGroupServiceGetFriendLastVisitTimeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplyForFriend": kitex.NewMethodInfo(
		applyForFriendHandler,
		newKitexGroupServiceApplyForFriendArgs,
		newKitexGroupServiceApplyForFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendApplyList": kitex.NewMethodInfo(
		getFriendApplyListHandler,
		newKitexGroupServiceGetFriendApplyListArgs,
		newKitexGroupServiceGetFriendApplyListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefuseFriendApply": kitex.NewMethodInfo(
		refuseFriendApplyHandler,
		newKitexGroupServiceRefuseFriendApplyArgs,
		newKitexGroupServiceRefuseFriendApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupAndSessionID": kitex.NewMethodInfo(
		getGroupAndSessionIDHandler,
		newKitexGroupServiceGetGroupAndSessionIDArgs,
		newKitexGroupServiceGetGroupAndSessionIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupOrSessionRoleAndExist": kitex.NewMethodInfo(
		getGroupOrSessionRoleAndExistHandler,
		newKitexGroupServiceGetGroupOrSessionRoleAndExistArgs,
		newKitexGroupServiceGetGroupOrSessionRoleAndExistResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetLastVisitTime": kitex.NewMethodInfo(
		setLastVisitTimeHandler,
		newKitexGroupServiceSetLastVisitTimeArgs,
		newKitexGroupServiceSetLastVisitTimeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupUserID": kitex.NewMethodInfo(
		getGroupUserIDHandler,
		newKitexGroupServiceGetGroupUserIDArgs,
		newKitexGroupServiceGetGroupUserIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetMute": kitex.NewMethodInfo(
		setMuteHandler,
		newKitexGroupServiceSetMuteArgs,
		newKitexGroupServiceSetMuteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReleaseMute": kitex.NewMethodInfo(
		releaseMuteHandler,
		newKitexGroupServiceReleaseMuteArgs,
		newKitexGroupServiceReleaseMuteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMuteStatus": kitex.NewMethodInfo(
		getMuteStatusHandler,
		newKitexGroupServiceGetMuteStatusArgs,
		newKitexGroupServiceGetMuteStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	kitexGroupServiceServiceInfo                = NewServiceInfo()
	kitexGroupServiceServiceInfoForClient       = NewServiceInfoForClient()
	kitexGroupServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return kitexGroupServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return kitexGroupServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return kitexGroupServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KitexGroupService"
	handlerType := (*kitexgroupservice.KitexGroupService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kitexgroupservice",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getGroupInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetGroupInfoArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetGroupInfoResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetGroupInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetGroupInfoArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupInfoArgs()
}

func newKitexGroupServiceGetGroupInfoResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupInfoResult()
}

func changeGroupInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceChangeGroupInfoArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceChangeGroupInfoResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).ChangeGroupInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceChangeGroupInfoArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceChangeGroupInfoArgs()
}

func newKitexGroupServiceChangeGroupInfoResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceChangeGroupInfoResult()
}

func searchGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceSearchGroupArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceSearchGroupResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).SearchGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceSearchGroupArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSearchGroupArgs()
}

func newKitexGroupServiceSearchGroupResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSearchGroupResult()
}

func createGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceCreateGroupArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceCreateGroupResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).CreateGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceCreateGroupArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceCreateGroupArgs()
}

func newKitexGroupServiceCreateGroupResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceCreateGroupResult()
}

func deleteGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceDeleteGroupArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceDeleteGroupResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).DeleteGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceDeleteGroupArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceDeleteGroupArgs()
}

func newKitexGroupServiceDeleteGroupResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceDeleteGroupResult()
}

func leaveGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceLeaveGroupArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceLeaveGroupResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).LeaveGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceLeaveGroupArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceLeaveGroupArgs()
}

func newKitexGroupServiceLeaveGroupResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceLeaveGroupResult()
}

func setGroupApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceSetGroupApplyArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceSetGroupApplyResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).SetGroupApply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceSetGroupApplyArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSetGroupApplyArgs()
}

func newKitexGroupServiceSetGroupApplyResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSetGroupApplyResult()
}

func getGroupApplyListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetGroupApplyListArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetGroupApplyListResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetGroupApplyList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetGroupApplyListArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupApplyListArgs()
}

func newKitexGroupServiceGetGroupApplyListResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupApplyListResult()
}

func getLastVisitTimeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetLastVisitTimeArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetLastVisitTimeResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetLastVisitTime(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetLastVisitTimeArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetLastVisitTimeArgs()
}

func newKitexGroupServiceGetLastVisitTimeResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetLastVisitTimeResult()
}

func agreeGroupApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceAgreeGroupApplyArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceAgreeGroupApplyResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).AgreeGroupApply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceAgreeGroupApplyArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceAgreeGroupApplyArgs()
}

func newKitexGroupServiceAgreeGroupApplyResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceAgreeGroupApplyResult()
}

func refuseGroupApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceRefuseGroupApplyArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceRefuseGroupApplyResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).RefuseGroupApply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceRefuseGroupApplyArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceRefuseGroupApplyArgs()
}

func newKitexGroupServiceRefuseGroupApplyResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceRefuseGroupApplyResult()
}

func transformGroupOwnerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceTransformGroupOwnerArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceTransformGroupOwnerResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).TransformGroupOwner(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceTransformGroupOwnerArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceTransformGroupOwnerArgs()
}

func newKitexGroupServiceTransformGroupOwnerResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceTransformGroupOwnerResult()
}

func kickOutGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceKickOutGroupArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceKickOutGroupResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).KickOutGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceKickOutGroupArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceKickOutGroupArgs()
}

func newKitexGroupServiceKickOutGroupResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceKickOutGroupResult()
}

func setManagerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceSetManagerArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceSetManagerResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).SetManager(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceSetManagerArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSetManagerArgs()
}

func newKitexGroupServiceSetManagerResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSetManagerResult()
}

func revokeManagerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceRevokeManagerArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceRevokeManagerResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).RevokeManager(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceRevokeManagerArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceRevokeManagerArgs()
}

func newKitexGroupServiceRevokeManagerResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceRevokeManagerResult()
}

func getGroupInfoWithUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetGroupInfoWithUserArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetGroupInfoWithUserResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetGroupInfoWithUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetGroupInfoWithUserArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupInfoWithUserArgs()
}

func newKitexGroupServiceGetGroupInfoWithUserResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupInfoWithUserResult()
}

func updateGroupInfoWithUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceUpdateGroupInfoWithUserArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceUpdateGroupInfoWithUserResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).UpdateGroupInfoWithUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceUpdateGroupInfoWithUserArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceUpdateGroupInfoWithUserArgs()
}

func newKitexGroupServiceUpdateGroupInfoWithUserResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceUpdateGroupInfoWithUserResult()
}

func creatSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceCreatSessionArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceCreatSessionResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).CreatSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceCreatSessionArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceCreatSessionArgs()
}

func newKitexGroupServiceCreatSessionResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceCreatSessionResult()
}

func deleteSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceDeleteSessionArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceDeleteSessionResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).DeleteSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceDeleteSessionArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceDeleteSessionArgs()
}

func newKitexGroupServiceDeleteSessionResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceDeleteSessionResult()
}

func getFriendLastVisitTimeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetFriendLastVisitTimeArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetFriendLastVisitTimeResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetFriendLastVisitTime(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetFriendLastVisitTimeArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetFriendLastVisitTimeArgs()
}

func newKitexGroupServiceGetFriendLastVisitTimeResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetFriendLastVisitTimeResult()
}

func applyForFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceApplyForFriendArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceApplyForFriendResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).ApplyForFriend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceApplyForFriendArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceApplyForFriendArgs()
}

func newKitexGroupServiceApplyForFriendResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceApplyForFriendResult()
}

func getFriendApplyListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetFriendApplyListArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetFriendApplyListResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetFriendApplyList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetFriendApplyListArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetFriendApplyListArgs()
}

func newKitexGroupServiceGetFriendApplyListResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetFriendApplyListResult()
}

func refuseFriendApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceRefuseFriendApplyArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceRefuseFriendApplyResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).RefuseFriendApply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceRefuseFriendApplyArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceRefuseFriendApplyArgs()
}

func newKitexGroupServiceRefuseFriendApplyResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceRefuseFriendApplyResult()
}

func getGroupAndSessionIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetGroupAndSessionIDArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetGroupAndSessionIDResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetGroupAndSessionID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetGroupAndSessionIDArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupAndSessionIDArgs()
}

func newKitexGroupServiceGetGroupAndSessionIDResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupAndSessionIDResult()
}

func getGroupOrSessionRoleAndExistHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetGroupOrSessionRoleAndExistArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetGroupOrSessionRoleAndExistResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetGroupOrSessionRoleAndExist(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetGroupOrSessionRoleAndExistArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupOrSessionRoleAndExistArgs()
}

func newKitexGroupServiceGetGroupOrSessionRoleAndExistResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupOrSessionRoleAndExistResult()
}

func setLastVisitTimeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceSetLastVisitTimeArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceSetLastVisitTimeResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).SetLastVisitTime(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceSetLastVisitTimeArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSetLastVisitTimeArgs()
}

func newKitexGroupServiceSetLastVisitTimeResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSetLastVisitTimeResult()
}

func getGroupUserIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetGroupUserIDArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetGroupUserIDResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetGroupUserID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetGroupUserIDArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupUserIDArgs()
}

func newKitexGroupServiceGetGroupUserIDResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetGroupUserIDResult()
}

func setMuteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceSetMuteArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceSetMuteResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).SetMute(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceSetMuteArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSetMuteArgs()
}

func newKitexGroupServiceSetMuteResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceSetMuteResult()
}

func releaseMuteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceReleaseMuteArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceReleaseMuteResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).ReleaseMute(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceReleaseMuteArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceReleaseMuteArgs()
}

func newKitexGroupServiceReleaseMuteResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceReleaseMuteResult()
}

func getMuteStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservice.KitexGroupServiceGetMuteStatusArgs)
	realResult := result.(*kitexgroupservice.KitexGroupServiceGetMuteStatusResult)
	success, err := handler.(kitexgroupservice.KitexGroupService).GetMuteStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexGroupServiceGetMuteStatusArgs() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetMuteStatusArgs()
}

func newKitexGroupServiceGetMuteStatusResult() interface{} {
	return kitexgroupservice.NewKitexGroupServiceGetMuteStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetGroupInfo(ctx context.Context, req *kitexgroupservice.GetGroupInfoReq) (r *kitexgroupservice.GetGroupInfoResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetGroupInfoArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetGroupInfoResult
	if err = p.c.Call(ctx, "GetGroupInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeGroupInfo(ctx context.Context, req *kitexgroupservice.ChangeGroupInfoReq) (r *kitexgroupservice.ChangeGroupInfoResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceChangeGroupInfoArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceChangeGroupInfoResult
	if err = p.c.Call(ctx, "ChangeGroupInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchGroup(ctx context.Context, req *kitexgroupservice.SearchGroupReq) (r *kitexgroupservice.SearchGroupResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceSearchGroupArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceSearchGroupResult
	if err = p.c.Call(ctx, "SearchGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateGroup(ctx context.Context, req *kitexgroupservice.CreateGroupReq) (r *kitexgroupservice.CreateGroupResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceCreateGroupArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceCreateGroupResult
	if err = p.c.Call(ctx, "CreateGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteGroup(ctx context.Context, req *kitexgroupservice.DeleteGroupReq) (r *kitexgroupservice.DeleteGroupResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceDeleteGroupArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceDeleteGroupResult
	if err = p.c.Call(ctx, "DeleteGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LeaveGroup(ctx context.Context, req *kitexgroupservice.LeaveGroupReq) (r *kitexgroupservice.LeaveGroupResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceLeaveGroupArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceLeaveGroupResult
	if err = p.c.Call(ctx, "LeaveGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetGroupApply(ctx context.Context, req *kitexgroupservice.SetGroupApplyReq) (r *kitexgroupservice.SetGroupApplyResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceSetGroupApplyArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceSetGroupApplyResult
	if err = p.c.Call(ctx, "SetGroupApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupApplyList(ctx context.Context, req *kitexgroupservice.GetGroupApplyListReq) (r *kitexgroupservice.GetGroupApplyListResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetGroupApplyListArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetGroupApplyListResult
	if err = p.c.Call(ctx, "GetGroupApplyList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLastVisitTime(ctx context.Context, req *kitexgroupservice.GetLastVisitTimeReq) (r *kitexgroupservice.GetLastVisitTimeResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetLastVisitTimeArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetLastVisitTimeResult
	if err = p.c.Call(ctx, "GetLastVisitTime", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AgreeGroupApply(ctx context.Context, req *kitexgroupservice.AgreeGroupApplyReq) (r *kitexgroupservice.AgreeGroupApplyResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceAgreeGroupApplyArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceAgreeGroupApplyResult
	if err = p.c.Call(ctx, "AgreeGroupApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefuseGroupApply(ctx context.Context, req *kitexgroupservice.RefuseGroupApplyReq) (r *kitexgroupservice.RefuseGroupApplyResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceRefuseGroupApplyArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceRefuseGroupApplyResult
	if err = p.c.Call(ctx, "RefuseGroupApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TransformGroupOwner(ctx context.Context, req *kitexgroupservice.TransformGroupOwnerReq) (r *kitexgroupservice.TransformGroupOwnerResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceTransformGroupOwnerArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceTransformGroupOwnerResult
	if err = p.c.Call(ctx, "TransformGroupOwner", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) KickOutGroup(ctx context.Context, req *kitexgroupservice.KickOutGroupReq) (r *kitexgroupservice.KickOutGroupResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceKickOutGroupArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceKickOutGroupResult
	if err = p.c.Call(ctx, "KickOutGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetManager(ctx context.Context, req *kitexgroupservice.SetManagerReq) (r *kitexgroupservice.SetManagerResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceSetManagerArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceSetManagerResult
	if err = p.c.Call(ctx, "SetManager", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RevokeManager(ctx context.Context, req *kitexgroupservice.RevokeManagerReq) (r *kitexgroupservice.RevokeManagerResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceRevokeManagerArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceRevokeManagerResult
	if err = p.c.Call(ctx, "RevokeManager", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupInfoWithUser(ctx context.Context, req *kitexgroupservice.GetGroupInfoWithUserReq) (r *kitexgroupservice.GetGroupInfoWithUserResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetGroupInfoWithUserArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetGroupInfoWithUserResult
	if err = p.c.Call(ctx, "GetGroupInfoWithUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateGroupInfoWithUser(ctx context.Context, req *kitexgroupservice.UpdateGroupInfoWithUserReq) (r *kitexgroupservice.UpdateGroupInfoWithUserResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceUpdateGroupInfoWithUserArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceUpdateGroupInfoWithUserResult
	if err = p.c.Call(ctx, "UpdateGroupInfoWithUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatSession(ctx context.Context, req *kitexgroupservice.CreatSessionReq) (r *kitexgroupservice.CreatSessionResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceCreatSessionArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceCreatSessionResult
	if err = p.c.Call(ctx, "CreatSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteSession(ctx context.Context, req *kitexgroupservice.DeleteSessionReq) (r *kitexgroupservice.DeleteSessionResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceDeleteSessionArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceDeleteSessionResult
	if err = p.c.Call(ctx, "DeleteSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendLastVisitTime(ctx context.Context, req *kitexgroupservice.GetFriendLastVisitTimeReq) (r *kitexgroupservice.GetFriendLastVisitTimeResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetFriendLastVisitTimeArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetFriendLastVisitTimeResult
	if err = p.c.Call(ctx, "GetFriendLastVisitTime", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplyForFriend(ctx context.Context, req *kitexgroupservice.ApplyForFriendReq) (r *kitexgroupservice.ApplyForFriendResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceApplyForFriendArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceApplyForFriendResult
	if err = p.c.Call(ctx, "ApplyForFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendApplyList(ctx context.Context, req *kitexgroupservice.GetFriendApplyListReq) (r *kitexgroupservice.GetFriendApplyListResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetFriendApplyListArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetFriendApplyListResult
	if err = p.c.Call(ctx, "GetFriendApplyList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefuseFriendApply(ctx context.Context, req *kitexgroupservice.RefuseFriendApplyReq) (r *kitexgroupservice.RefuseFriendApplyResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceRefuseFriendApplyArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceRefuseFriendApplyResult
	if err = p.c.Call(ctx, "RefuseFriendApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupAndSessionID(ctx context.Context, req *kitexgroupservice.GetGroupAndSessionIDReq) (r *kitexgroupservice.GetGroupAndSessionIDResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetGroupAndSessionIDArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetGroupAndSessionIDResult
	if err = p.c.Call(ctx, "GetGroupAndSessionID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupOrSessionRoleAndExist(ctx context.Context, req *kitexgroupservice.GetGroupOrSessionRoleAndExistReq) (r *kitexgroupservice.GetGroupOrSessionRoleAndExistResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetGroupOrSessionRoleAndExistArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetGroupOrSessionRoleAndExistResult
	if err = p.c.Call(ctx, "GetGroupOrSessionRoleAndExist", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetLastVisitTime(ctx context.Context, req *kitexgroupservice.SetLastVisitTimeReq) (r *kitexgroupservice.SetLastVisitTimeResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceSetLastVisitTimeArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceSetLastVisitTimeResult
	if err = p.c.Call(ctx, "SetLastVisitTime", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupUserID(ctx context.Context, req *kitexgroupservice.GetGroupUserIDReq) (r *kitexgroupservice.GetGroupUserIDResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetGroupUserIDArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetGroupUserIDResult
	if err = p.c.Call(ctx, "GetGroupUserID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetMute(ctx context.Context, req *kitexgroupservice.SetMuteReq) (r *kitexgroupservice.SetMuteResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceSetMuteArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceSetMuteResult
	if err = p.c.Call(ctx, "SetMute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseMute(ctx context.Context, req *kitexgroupservice.ReleaseMuteReq) (r *kitexgroupservice.ReleaseMuteResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceReleaseMuteArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceReleaseMuteResult
	if err = p.c.Call(ctx, "ReleaseMute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMuteStatus(ctx context.Context, req *kitexgroupservice.GetMuteStatusReq) (r *kitexgroupservice.GetMuteStatusResp, err error) {
	var _args kitexgroupservice.KitexGroupServiceGetMuteStatusArgs
	_args.Req = req
	var _result kitexgroupservice.KitexGroupServiceGetMuteStatusResult
	if err = p.c.Call(ctx, "GetMuteStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
