// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexaiservice

import (
	kitexaiservice "aim/kitex_gen/kitexaiservice"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessageToAi(ctx context.Context, req *kitexaiservice.SendMessageToAiReq, callOptions ...callopt.Option) (r *kitexaiservice.SendMessageToAiResp, err error)
	DeleteChatContext(ctx context.Context, req *kitexaiservice.DeleteChatContextReq, callOptions ...callopt.Option) (r *kitexaiservice.DeleteChatContextResp, err error)
	GetAiConfig(ctx context.Context, req *kitexaiservice.GetAiConfigReq, callOptions ...callopt.Option) (r *kitexaiservice.GetAiConfigResp, err error)
	UpdateAiConfig(ctx context.Context, req *kitexaiservice.UpdateAiConfigReq, callOptions ...callopt.Option) (r *kitexaiservice.UpdateAiConfigResp, err error)
	DeleteAiConfig(ctx context.Context, req *kitexaiservice.DeleteAiConfigReq, callOptions ...callopt.Option) (r *kitexaiservice.DeleteAiConfigResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKitexAiServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKitexAiServiceClient struct {
	*kClient
}

func (p *kKitexAiServiceClient) SendMessageToAi(ctx context.Context, req *kitexaiservice.SendMessageToAiReq, callOptions ...callopt.Option) (r *kitexaiservice.SendMessageToAiResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessageToAi(ctx, req)
}

func (p *kKitexAiServiceClient) DeleteChatContext(ctx context.Context, req *kitexaiservice.DeleteChatContextReq, callOptions ...callopt.Option) (r *kitexaiservice.DeleteChatContextResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteChatContext(ctx, req)
}

func (p *kKitexAiServiceClient) GetAiConfig(ctx context.Context, req *kitexaiservice.GetAiConfigReq, callOptions ...callopt.Option) (r *kitexaiservice.GetAiConfigResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAiConfig(ctx, req)
}

func (p *kKitexAiServiceClient) UpdateAiConfig(ctx context.Context, req *kitexaiservice.UpdateAiConfigReq, callOptions ...callopt.Option) (r *kitexaiservice.UpdateAiConfigResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAiConfig(ctx, req)
}

func (p *kKitexAiServiceClient) DeleteAiConfig(ctx context.Context, req *kitexaiservice.DeleteAiConfigReq, callOptions ...callopt.Option) (r *kitexaiservice.DeleteAiConfigResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAiConfig(ctx, req)
}
