// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexcommonmodel

import (
	"fmt"
)

type KitexMessageInfo struct {
	GroupId             int64  `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	MessageId           int64  `thrift:"message_id,2" frugal:"2,default,i64" json:"message_id"`
	UserId              int64  `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	MessageContent      string `thrift:"message_content,4" frugal:"4,default,string" json:"message_content"`
	ContentType         string `thrift:"content_type,5" frugal:"5,default,string" json:"content_type"`
	VoiceDurationSecond int64  `thrift:"voice_duration_second,6" frugal:"6,default,i64" json:"voice_duration_second"`
	IsAi                bool   `thrift:"is_ai,7" frugal:"7,default,bool" json:"is_ai"`
	MessageType         string `thrift:"message_type,8" frugal:"8,default,string" json:"message_type"`
	SendTimeSecond      int64  `thrift:"send_time_second,9" frugal:"9,default,i64" json:"send_time_second"`
}

func NewKitexMessageInfo() *KitexMessageInfo {
	return &KitexMessageInfo{}
}

func (p *KitexMessageInfo) InitDefault() {
}

func (p *KitexMessageInfo) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *KitexMessageInfo) GetMessageId() (v int64) {
	return p.MessageId
}

func (p *KitexMessageInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *KitexMessageInfo) GetMessageContent() (v string) {
	return p.MessageContent
}

func (p *KitexMessageInfo) GetContentType() (v string) {
	return p.ContentType
}

func (p *KitexMessageInfo) GetVoiceDurationSecond() (v int64) {
	return p.VoiceDurationSecond
}

func (p *KitexMessageInfo) GetIsAi() (v bool) {
	return p.IsAi
}

func (p *KitexMessageInfo) GetMessageType() (v string) {
	return p.MessageType
}

func (p *KitexMessageInfo) GetSendTimeSecond() (v int64) {
	return p.SendTimeSecond
}
func (p *KitexMessageInfo) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *KitexMessageInfo) SetMessageId(val int64) {
	p.MessageId = val
}
func (p *KitexMessageInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *KitexMessageInfo) SetMessageContent(val string) {
	p.MessageContent = val
}
func (p *KitexMessageInfo) SetContentType(val string) {
	p.ContentType = val
}
func (p *KitexMessageInfo) SetVoiceDurationSecond(val int64) {
	p.VoiceDurationSecond = val
}
func (p *KitexMessageInfo) SetIsAi(val bool) {
	p.IsAi = val
}
func (p *KitexMessageInfo) SetMessageType(val string) {
	p.MessageType = val
}
func (p *KitexMessageInfo) SetSendTimeSecond(val int64) {
	p.SendTimeSecond = val
}

func (p *KitexMessageInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KitexMessageInfo(%+v)", *p)
}

var fieldIDToName_KitexMessageInfo = map[int16]string{
	1: "group_id",
	2: "message_id",
	3: "user_id",
	4: "message_content",
	5: "content_type",
	6: "voice_duration_second",
	7: "is_ai",
	8: "message_type",
	9: "send_time_second",
}
