// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexfileservice

import (
	kitexfileservice "aim/kitex_gen/kitexfileservice"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateFile(ctx context.Context, req *kitexfileservice.CreateFileReq, callOptions ...callopt.Option) (r *kitexfileservice.CreateFileResp, err error)
	DeleteFile(ctx context.Context, req *kitexfileservice.DeleteFileReq, callOptions ...callopt.Option) (r *kitexfileservice.DeleteFileResp, err error)
	GetFile(ctx context.Context, req *kitexfileservice.GetFileReq, callOptions ...callopt.Option) (r *kitexfileservice.GetFileResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKitexFileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKitexFileServiceClient struct {
	*kClient
}

func (p *kKitexFileServiceClient) CreateFile(ctx context.Context, req *kitexfileservice.CreateFileReq, callOptions ...callopt.Option) (r *kitexfileservice.CreateFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateFile(ctx, req)
}

func (p *kKitexFileServiceClient) DeleteFile(ctx context.Context, req *kitexfileservice.DeleteFileReq, callOptions ...callopt.Option) (r *kitexfileservice.DeleteFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFile(ctx, req)
}

func (p *kKitexFileServiceClient) GetFile(ctx context.Context, req *kitexfileservice.GetFileReq, callOptions ...callopt.Option) (r *kitexfileservice.GetFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFile(ctx, req)
}
