// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexmessageservice

import (
	kitexmessageservice "aim/kitex_gen/kitexmessageservice"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessage(ctx context.Context, req *kitexmessageservice.SendMessageReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendMessageResp, err error)
	SendFile(ctx context.Context, req *kitexmessageservice.SendFileReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendFileResp, err error)
	SendVoice(ctx context.Context, req *kitexmessageservice.SendVoiceReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendVoiceResp, err error)
	SendPicture(ctx context.Context, req *kitexmessageservice.SendPictureReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendPictureResp, err error)
	WithdrawMessage(ctx context.Context, req *kitexmessageservice.WithdrawMessageReq, callOptions ...callopt.Option) (r *kitexmessageservice.WithdrawMessageResp, err error)
	DeleteMessageAllGroup(ctx context.Context, req *kitexmessageservice.DeleteMessageAllGroupReq, callOptions ...callopt.Option) (r *kitexmessageservice.DeleteMessageAllGroupResp, err error)
	GetMessageList(ctx context.Context, req *kitexmessageservice.GetMessageListReq, callOptions ...callopt.Option) (r *kitexmessageservice.GetMessageListResp, err error)
	GetNewMessage(ctx context.Context, req *kitexmessageservice.GetNewMessageReq, callOptions ...callopt.Option) (r *kitexmessageservice.GetNewMessageResp, err error)
	GetFileContent(ctx context.Context, req *kitexmessageservice.GetFileContentReq, callOptions ...callopt.Option) (r *kitexmessageservice.GetFileContentResp, err error)
	SendGroupNotice(ctx context.Context, req *kitexmessageservice.SendGroupNoticeReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendGroupNoticeResp, err error)
	SetOfflineMessage(ctx context.Context, req *kitexmessageservice.SetOfflineMessageReq, callOptions ...callopt.Option) (r *kitexmessageservice.SetOfflineMessageResp, err error)
	GetOfflineMessageList(ctx context.Context, req *kitexmessageservice.GetOfflineMessageListReq, callOptions ...callopt.Option) (r *kitexmessageservice.GetOfflineMessageListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKitexMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKitexMessageServiceClient struct {
	*kClient
}

func (p *kKitexMessageServiceClient) SendMessage(ctx context.Context, req *kitexmessageservice.SendMessageReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, req)
}

func (p *kKitexMessageServiceClient) SendFile(ctx context.Context, req *kitexmessageservice.SendFileReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendFile(ctx, req)
}

func (p *kKitexMessageServiceClient) SendVoice(ctx context.Context, req *kitexmessageservice.SendVoiceReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendVoiceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendVoice(ctx, req)
}

func (p *kKitexMessageServiceClient) SendPicture(ctx context.Context, req *kitexmessageservice.SendPictureReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendPictureResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendPicture(ctx, req)
}

func (p *kKitexMessageServiceClient) WithdrawMessage(ctx context.Context, req *kitexmessageservice.WithdrawMessageReq, callOptions ...callopt.Option) (r *kitexmessageservice.WithdrawMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.WithdrawMessage(ctx, req)
}

func (p *kKitexMessageServiceClient) DeleteMessageAllGroup(ctx context.Context, req *kitexmessageservice.DeleteMessageAllGroupReq, callOptions ...callopt.Option) (r *kitexmessageservice.DeleteMessageAllGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteMessageAllGroup(ctx, req)
}

func (p *kKitexMessageServiceClient) GetMessageList(ctx context.Context, req *kitexmessageservice.GetMessageListReq, callOptions ...callopt.Option) (r *kitexmessageservice.GetMessageListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMessageList(ctx, req)
}

func (p *kKitexMessageServiceClient) GetNewMessage(ctx context.Context, req *kitexmessageservice.GetNewMessageReq, callOptions ...callopt.Option) (r *kitexmessageservice.GetNewMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNewMessage(ctx, req)
}

func (p *kKitexMessageServiceClient) GetFileContent(ctx context.Context, req *kitexmessageservice.GetFileContentReq, callOptions ...callopt.Option) (r *kitexmessageservice.GetFileContentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFileContent(ctx, req)
}

func (p *kKitexMessageServiceClient) SendGroupNotice(ctx context.Context, req *kitexmessageservice.SendGroupNoticeReq, callOptions ...callopt.Option) (r *kitexmessageservice.SendGroupNoticeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendGroupNotice(ctx, req)
}

func (p *kKitexMessageServiceClient) SetOfflineMessage(ctx context.Context, req *kitexmessageservice.SetOfflineMessageReq, callOptions ...callopt.Option) (r *kitexmessageservice.SetOfflineMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetOfflineMessage(ctx, req)
}

func (p *kKitexMessageServiceClient) GetOfflineMessageList(ctx context.Context, req *kitexmessageservice.GetOfflineMessageListReq, callOptions ...callopt.Option) (r *kitexmessageservice.GetOfflineMessageListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOfflineMessageList(ctx, req)
}
