// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitexmessageservice

import (
	kitexmessageservice "aim/kitex_gen/kitexmessageservice"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendMessage": kitex.NewMethodInfo(
		sendMessageHandler,
		newKitexMessageServiceSendMessageArgs,
		newKitexMessageServiceSendMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendFile": kitex.NewMethodInfo(
		sendFileHandler,
		newKitexMessageServiceSendFileArgs,
		newKitexMessageServiceSendFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendVoice": kitex.NewMethodInfo(
		sendVoiceHandler,
		newKitexMessageServiceSendVoiceArgs,
		newKitexMessageServiceSendVoiceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendPicture": kitex.NewMethodInfo(
		sendPictureHandler,
		newKitexMessageServiceSendPictureArgs,
		newKitexMessageServiceSendPictureResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"WithdrawMessage": kitex.NewMethodInfo(
		withdrawMessageHandler,
		newKitexMessageServiceWithdrawMessageArgs,
		newKitexMessageServiceWithdrawMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteMessageAllGroup": kitex.NewMethodInfo(
		deleteMessageAllGroupHandler,
		newKitexMessageServiceDeleteMessageAllGroupArgs,
		newKitexMessageServiceDeleteMessageAllGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMessageList": kitex.NewMethodInfo(
		getMessageListHandler,
		newKitexMessageServiceGetMessageListArgs,
		newKitexMessageServiceGetMessageListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetNewMessage": kitex.NewMethodInfo(
		getNewMessageHandler,
		newKitexMessageServiceGetNewMessageArgs,
		newKitexMessageServiceGetNewMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFileContent": kitex.NewMethodInfo(
		getFileContentHandler,
		newKitexMessageServiceGetFileContentArgs,
		newKitexMessageServiceGetFileContentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendGroupNotice": kitex.NewMethodInfo(
		sendGroupNoticeHandler,
		newKitexMessageServiceSendGroupNoticeArgs,
		newKitexMessageServiceSendGroupNoticeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetOfflineMessage": kitex.NewMethodInfo(
		setOfflineMessageHandler,
		newKitexMessageServiceSetOfflineMessageArgs,
		newKitexMessageServiceSetOfflineMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOfflineMessageList": kitex.NewMethodInfo(
		getOfflineMessageListHandler,
		newKitexMessageServiceGetOfflineMessageListArgs,
		newKitexMessageServiceGetOfflineMessageListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	kitexMessageServiceServiceInfo                = NewServiceInfo()
	kitexMessageServiceServiceInfoForClient       = NewServiceInfoForClient()
	kitexMessageServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return kitexMessageServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return kitexMessageServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return kitexMessageServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KitexMessageService"
	handlerType := (*kitexmessageservice.KitexMessageService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kitexmessageservice",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceSendMessageArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceSendMessageResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).SendMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceSendMessageArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendMessageArgs()
}

func newKitexMessageServiceSendMessageResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendMessageResult()
}

func sendFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceSendFileArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceSendFileResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).SendFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceSendFileArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendFileArgs()
}

func newKitexMessageServiceSendFileResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendFileResult()
}

func sendVoiceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceSendVoiceArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceSendVoiceResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).SendVoice(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceSendVoiceArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendVoiceArgs()
}

func newKitexMessageServiceSendVoiceResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendVoiceResult()
}

func sendPictureHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceSendPictureArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceSendPictureResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).SendPicture(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceSendPictureArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendPictureArgs()
}

func newKitexMessageServiceSendPictureResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendPictureResult()
}

func withdrawMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceWithdrawMessageArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceWithdrawMessageResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).WithdrawMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceWithdrawMessageArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceWithdrawMessageArgs()
}

func newKitexMessageServiceWithdrawMessageResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceWithdrawMessageResult()
}

func deleteMessageAllGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceDeleteMessageAllGroupArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceDeleteMessageAllGroupResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).DeleteMessageAllGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceDeleteMessageAllGroupArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceDeleteMessageAllGroupArgs()
}

func newKitexMessageServiceDeleteMessageAllGroupResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceDeleteMessageAllGroupResult()
}

func getMessageListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceGetMessageListArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceGetMessageListResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).GetMessageList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceGetMessageListArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceGetMessageListArgs()
}

func newKitexMessageServiceGetMessageListResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceGetMessageListResult()
}

func getNewMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceGetNewMessageArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceGetNewMessageResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).GetNewMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceGetNewMessageArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceGetNewMessageArgs()
}

func newKitexMessageServiceGetNewMessageResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceGetNewMessageResult()
}

func getFileContentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceGetFileContentArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceGetFileContentResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).GetFileContent(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceGetFileContentArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceGetFileContentArgs()
}

func newKitexMessageServiceGetFileContentResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceGetFileContentResult()
}

func sendGroupNoticeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceSendGroupNoticeArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceSendGroupNoticeResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).SendGroupNotice(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceSendGroupNoticeArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendGroupNoticeArgs()
}

func newKitexMessageServiceSendGroupNoticeResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSendGroupNoticeResult()
}

func setOfflineMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceSetOfflineMessageArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceSetOfflineMessageResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).SetOfflineMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceSetOfflineMessageArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSetOfflineMessageArgs()
}

func newKitexMessageServiceSetOfflineMessageResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceSetOfflineMessageResult()
}

func getOfflineMessageListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexmessageservice.KitexMessageServiceGetOfflineMessageListArgs)
	realResult := result.(*kitexmessageservice.KitexMessageServiceGetOfflineMessageListResult)
	success, err := handler.(kitexmessageservice.KitexMessageService).GetOfflineMessageList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKitexMessageServiceGetOfflineMessageListArgs() interface{} {
	return kitexmessageservice.NewKitexMessageServiceGetOfflineMessageListArgs()
}

func newKitexMessageServiceGetOfflineMessageListResult() interface{} {
	return kitexmessageservice.NewKitexMessageServiceGetOfflineMessageListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendMessage(ctx context.Context, req *kitexmessageservice.SendMessageReq) (r *kitexmessageservice.SendMessageResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceSendMessageArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceSendMessageResult
	if err = p.c.Call(ctx, "SendMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendFile(ctx context.Context, req *kitexmessageservice.SendFileReq) (r *kitexmessageservice.SendFileResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceSendFileArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceSendFileResult
	if err = p.c.Call(ctx, "SendFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendVoice(ctx context.Context, req *kitexmessageservice.SendVoiceReq) (r *kitexmessageservice.SendVoiceResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceSendVoiceArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceSendVoiceResult
	if err = p.c.Call(ctx, "SendVoice", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendPicture(ctx context.Context, req *kitexmessageservice.SendPictureReq) (r *kitexmessageservice.SendPictureResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceSendPictureArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceSendPictureResult
	if err = p.c.Call(ctx, "SendPicture", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) WithdrawMessage(ctx context.Context, req *kitexmessageservice.WithdrawMessageReq) (r *kitexmessageservice.WithdrawMessageResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceWithdrawMessageArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceWithdrawMessageResult
	if err = p.c.Call(ctx, "WithdrawMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteMessageAllGroup(ctx context.Context, req *kitexmessageservice.DeleteMessageAllGroupReq) (r *kitexmessageservice.DeleteMessageAllGroupResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceDeleteMessageAllGroupArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceDeleteMessageAllGroupResult
	if err = p.c.Call(ctx, "DeleteMessageAllGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMessageList(ctx context.Context, req *kitexmessageservice.GetMessageListReq) (r *kitexmessageservice.GetMessageListResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceGetMessageListArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceGetMessageListResult
	if err = p.c.Call(ctx, "GetMessageList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetNewMessage(ctx context.Context, req *kitexmessageservice.GetNewMessageReq) (r *kitexmessageservice.GetNewMessageResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceGetNewMessageArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceGetNewMessageResult
	if err = p.c.Call(ctx, "GetNewMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFileContent(ctx context.Context, req *kitexmessageservice.GetFileContentReq) (r *kitexmessageservice.GetFileContentResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceGetFileContentArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceGetFileContentResult
	if err = p.c.Call(ctx, "GetFileContent", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendGroupNotice(ctx context.Context, req *kitexmessageservice.SendGroupNoticeReq) (r *kitexmessageservice.SendGroupNoticeResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceSendGroupNoticeArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceSendGroupNoticeResult
	if err = p.c.Call(ctx, "SendGroupNotice", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetOfflineMessage(ctx context.Context, req *kitexmessageservice.SetOfflineMessageReq) (r *kitexmessageservice.SetOfflineMessageResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceSetOfflineMessageArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceSetOfflineMessageResult
	if err = p.c.Call(ctx, "SetOfflineMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOfflineMessageList(ctx context.Context, req *kitexmessageservice.GetOfflineMessageListReq) (r *kitexmessageservice.GetOfflineMessageListResp, err error) {
	var _args kitexmessageservice.KitexMessageServiceGetOfflineMessageListArgs
	_args.Req = req
	var _result kitexmessageservice.KitexMessageServiceGetOfflineMessageListResult
	if err = p.c.Call(ctx, "GetOfflineMessageList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
